/* Auto-generated by gameboy/tools/gen-foundation-foods.mjs — do not edit by hand. */
/* Source: data/common_foundation_foods.json. */
#ifndef COMMON_FOODS_H
#define COMMON_FOODS_H

#include <stdint.h>

#include "foundation_foods.h" /* for foundation_food_t */

#define COMMON_FOOD_COUNT 304u

/* The table and its name strings live in this ROM bank. Callers must
 * SWITCH_ROM(COMMON_FOODS_BANK) before dereferencing the array. */
#define COMMON_FOODS_BANK 3

extern const foundation_food_t common_foods[COMMON_FOOD_COUNT];

#endif /* COMMON_FOODS_H */
