/* Auto-generated by gameboy/tools/gen-exercises.mjs — do not edit by hand. */
/* Source: data/exercisesData.json. */
#ifndef MUSCLOG_EXERCISES_H
#define MUSCLOG_EXERCISES_H

#include <stdint.h>

typedef enum {
    EX_MUSCLE_ABDOMEN = 0,
    EX_MUSCLE_ARMS = 1,
    EX_MUSCLE_BACK = 2,
    EX_MUSCLE_CHEST = 3,
    EX_MUSCLE_CORE = 4,
    EX_MUSCLE_FULL_BODY = 5,
    EX_MUSCLE_GLUTES = 6,
    EX_MUSCLE_LEGS = 7,
    EX_MUSCLE_SHOULDERS = 8,
} exercise_muscle_group_t;

#define EXERCISE_MUSCLE_GROUP_COUNT 9u

typedef enum {
    EX_EQUIPMENT_BARBELL = 0,
    EX_EQUIPMENT_BODYWEIGHT = 1,
    EX_EQUIPMENT_CABLE = 2,
    EX_EQUIPMENT_CARDIO = 3,
    EX_EQUIPMENT_DUMBBELL = 4,
    EX_EQUIPMENT_KETTLEBELL = 5,
    EX_EQUIPMENT_MEDICINE_BALL = 6,
    EX_EQUIPMENT_OTHER = 7,
    EX_EQUIPMENT_PLATE_MACHINE = 8,
    EX_EQUIPMENT_RESISTANCE_BAND = 9,
    EX_EQUIPMENT_SMITH_MACHINE = 10,
} exercise_equipment_type_t;

#define EXERCISE_EQUIPMENT_TYPE_COUNT 11u

/* One bundled exercise. The table order follows exerciseIndex, so the stable
 * exercise id is the zero-based array index + 1.
 * load_multiplier_centi stores loadMultiplier * 100 (1.45 -> 145). */
typedef struct {
    const char *name;
    uint8_t muscle_group;            /* exercise_muscle_group_t */
    uint8_t equipment_type;          /* exercise_equipment_type_t */
    uint16_t load_multiplier_centi;
} exercise_t;

#define EXERCISE_COUNT 198u
#define EXERCISE_LOAD_MULTIPLIER_SCALE 100u

/* The table and its name strings live in this ROM bank. Callers must
 * SWITCH_ROM(EXERCISES_BANK) before dereferencing the arrays. */
#define EXERCISES_BANK 6

extern const char * const exercise_muscle_group_names[EXERCISE_MUSCLE_GROUP_COUNT];
extern const char * const exercise_equipment_type_names[EXERCISE_EQUIPMENT_TYPE_COUNT];
extern const exercise_t exercises[EXERCISE_COUNT];

#endif /* MUSCLOG_EXERCISES_H */
