/* Auto-generated by gameboy/tools/gen-exercises.mjs — do not edit by hand. */
/* Source: data/exercisesData.json. */
#pragma bank 6
#include "exercises.h"

const char * const exercise_muscle_group_names[EXERCISE_MUSCLE_GROUP_COUNT] = {
    "abdomen",
    "arms",
    "back",
    "chest",
    "core",
    "full_body",
    "glutes",
    "legs",
    "shoulders",
};

const char * const exercise_equipment_type_names[EXERCISE_EQUIPMENT_TYPE_COUNT] = {
    "barbell",
    "bodyweight",
    "cable",
    "cardio",
    "dumbbell",
    "kettlebell",
    "medicine_ball",
    "other",
    "plate_machine",
    "resistance_band",
    "smith_machine",
};

const exercise_t exercises[EXERCISE_COUNT] = {
    { "Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_BARBELL, 100u }, /* 1 */
    { "Inclined Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_BARBELL, 90u }, /* 2 */
    { "Declined Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_BARBELL, 110u }, /* 3 */
    { "Overhead Shoulder Press", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_BARBELL, 60u }, /* 4 */
    { "Deadlift", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 180u }, /* 5 */
    { "Pec Fly Machine", EX_MUSCLE_CHEST, EX_EQUIPMENT_CABLE, 50u }, /* 6 */
    { "Leg Extension Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 50u }, /* 7 */
    { "Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 140u }, /* 8 */
    { "Barbell Back Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 140u }, /* 9 */
    { "Leg Press Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 350u }, /* 10 */
    { "Lat Pulldown", EX_MUSCLE_BACK, EX_EQUIPMENT_PLATE_MACHINE, 70u }, /* 11 */
    { "Pull-Up", EX_MUSCLE_BACK, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 12 */
    { "Seated Row", EX_MUSCLE_BACK, EX_EQUIPMENT_PLATE_MACHINE, 70u }, /* 13 */
    { "Bicep Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 35u }, /* 14 */
    { "Tricep Overhead Extension", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 25u }, /* 15 */
    { "Leg Curl Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 40u }, /* 16 */
    { "Lateral Raise", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 10u }, /* 17 */
    { "Front Raise", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 8u }, /* 18 */
    { "Calf Raise", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 100u }, /* 19 */
    { "Hammer Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 18u }, /* 20 */
    { "Preacher Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_BARBELL, 25u }, /* 21 */
    { "Cable Tricep Pushdown", EX_MUSCLE_ARMS, EX_EQUIPMENT_CABLE, 35u }, /* 22 */
    { "Chest Press Machine", EX_MUSCLE_CHEST, EX_EQUIPMENT_PLATE_MACHINE, 90u }, /* 23 */
    { "Smith Machine Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_SMITH_MACHINE, 130u }, /* 24 */
    { "T-Bar Row", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 90u }, /* 25 */
    { "Bent Over Row", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 80u }, /* 26 */
    { "Upright Row", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_BARBELL, 40u }, /* 27 */
    { "Dumbbell Fly", EX_MUSCLE_CHEST, EX_EQUIPMENT_DUMBBELL, 15u }, /* 28 */
    { "Incline Dumbbell Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_DUMBBELL, 30u }, /* 29 */
    { "Machine Shoulder Press", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_PLATE_MACHINE, 60u }, /* 30 */
    { "Reverse Pec Deck Fly", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_PLATE_MACHINE, 50u }, /* 31 */
    { "Cable Crossover", EX_MUSCLE_CHEST, EX_EQUIPMENT_CABLE, 30u }, /* 32 */
    { "Seated Calf Raise", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 80u }, /* 33 */
    { "Standing Calf Raise", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 100u }, /* 34 */
    { "Romanian Deadlift", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 100u }, /* 35 */
    { "Glute Bridge", EX_MUSCLE_GLUTES, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 36 */
    { "Hip Thrust", EX_MUSCLE_GLUTES, EX_EQUIPMENT_BARBELL, 140u }, /* 37 */
    { "Cable Bicep Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_CABLE, 25u }, /* 38 */
    { "Dumbbell Shoulder Press", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 25u }, /* 39 */
    { "Smith Machine Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_SMITH_MACHINE, 100u }, /* 40 */
    { "Hack Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 150u }, /* 41 */
    { "Reverse Lunge", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 30u }, /* 42 */
    { "Step-Up", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 50u }, /* 43 */
    { "Kettlebell Swing", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_KETTLEBELL, 40u }, /* 44 */
    { "Goblet Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_KETTLEBELL, 40u }, /* 45 */
    { "Sumo Deadlift", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 180u }, /* 46 */
    { "Hip Abduction Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 60u }, /* 47 */
    { "Hip Adduction Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 60u }, /* 48 */
    { "Cable Face Pull", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_CABLE, 30u }, /* 49 */
    { "Incline Dumbbell Fly", EX_MUSCLE_CHEST, EX_EQUIPMENT_DUMBBELL, 15u }, /* 50 */
    { "Dips", EX_MUSCLE_ARMS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 51 */
    { "Push-Up", EX_MUSCLE_CHEST, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 52 */
    { "Plank", EX_MUSCLE_CORE, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 53 */
    { "Russian Twist", EX_MUSCLE_CORE, EX_EQUIPMENT_DUMBBELL, 10u }, /* 54 */
    { "Hanging Leg Raise", EX_MUSCLE_ABDOMEN, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 55 */
    { "Mountain Climbers", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 56 */
    { "Burpees", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 57 */
    { "Box Jump", EX_MUSCLE_LEGS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 58 */
    { "Turkish Get-Up", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_KETTLEBELL, 20u }, /* 59 */
    { "Farmer's Walk", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_DUMBBELL, 60u }, /* 60 */
    { "Snatch", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 70u }, /* 61 */
    { "Clean and Jerk", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 90u }, /* 62 */
    { "Battle Ropes", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_OTHER, 0u }, /* 63 */
    { "Crunch Machine", EX_MUSCLE_ABDOMEN, EX_EQUIPMENT_PLATE_MACHINE, 50u }, /* 64 */
    { "Chest Supported Row Machine", EX_MUSCLE_BACK, EX_EQUIPMENT_PLATE_MACHINE, 80u }, /* 65 */
    { "Barbell Row", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 80u }, /* 66 */
    { "Skull Crusher", EX_MUSCLE_ARMS, EX_EQUIPMENT_BARBELL, 30u }, /* 67 */
    { "Bulgarian Split Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 40u }, /* 68 */
    { "Pallof Press", EX_MUSCLE_CORE, EX_EQUIPMENT_CABLE, 20u }, /* 69 */
    { "Hanging Knee Raise", EX_MUSCLE_ABDOMEN, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 70 */
    { "Landmine Press", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_BARBELL, 50u }, /* 71 */
    { "Landmine Row", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 60u }, /* 72 */
    { "Donkey Calf Raise", EX_MUSCLE_LEGS, EX_EQUIPMENT_OTHER, 100u }, /* 73 */
    { "Jump Rope", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_CARDIO, 0u }, /* 74 */
    { "Running", EX_MUSCLE_LEGS, EX_EQUIPMENT_CARDIO, 0u }, /* 75 */
    { "Cycling", EX_MUSCLE_LEGS, EX_EQUIPMENT_CARDIO, 0u }, /* 76 */
    { "Rowing Machine", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_CARDIO, 0u }, /* 77 */
    { "Elliptical Trainer", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_CARDIO, 0u }, /* 78 */
    { "High-Intensity Interval Training (HIIT)", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_CARDIO, 0u }, /* 79 */
    { "Stair Climber", EX_MUSCLE_LEGS, EX_EQUIPMENT_CARDIO, 0u }, /* 80 */
    { "Aerobics", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_CARDIO, 0u }, /* 81 */
    { "Dance Cardio", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_CARDIO, 0u }, /* 82 */
    { "Shadow Boxing", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_CARDIO, 0u }, /* 83 */
    { "Narrow Grip Lat Pulldown", EX_MUSCLE_BACK, EX_EQUIPMENT_PLATE_MACHINE, 70u }, /* 84 */
    { "Supinated Lat Pulldown", EX_MUSCLE_BACK, EX_EQUIPMENT_PLATE_MACHINE, 70u }, /* 85 */
    { "Cable Pullover", EX_MUSCLE_BACK, EX_EQUIPMENT_CABLE, 30u }, /* 86 */
    { "Dumbbell Pullover", EX_MUSCLE_CHEST, EX_EQUIPMENT_DUMBBELL, 30u }, /* 87 */
    { "Reverse Grip Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_BARBELL, 80u }, /* 88 */
    { "Cable Chest Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_CABLE, 30u }, /* 89 */
    { "Cable Front Raise", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_CABLE, 8u }, /* 90 */
    { "Cable Lateral Raise", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_CABLE, 10u }, /* 91 */
    { "Single-Arm Dumbbell Row", EX_MUSCLE_BACK, EX_EQUIPMENT_DUMBBELL, 40u }, /* 92 */
    { "Dumbbell Shrug", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 50u }, /* 93 */
    { "Lying Leg Curl", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 40u }, /* 94 */
    { "Good Morning", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 70u }, /* 95 */
    { "Zercher Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 85u }, /* 96 */
    { "Sissy Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 97 */
    { "Jefferson Deadlift", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 140u }, /* 98 */
    { "Cossack Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 30u }, /* 99 */
    { "Dragon Flag", EX_MUSCLE_CORE, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 100 */
    { "Hollow Body Hold", EX_MUSCLE_CORE, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 101 */
    { "Reverse Crunch", EX_MUSCLE_ABDOMEN, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 102 */
    { "Ab Wheel Rollout", EX_MUSCLE_CORE, EX_EQUIPMENT_OTHER, 0u }, /* 103 */
    { "Pike Push-Up", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 104 */
    { "Cable Crunch", EX_MUSCLE_ABDOMEN, EX_EQUIPMENT_CABLE, 40u }, /* 105 */
    { "Dumbbell Triceps Kickback", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 20u }, /* 106 */
    { "Two-Arm Dumbbell Triceps Kickback", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 22u }, /* 107 */
    { "Seated Bent-Over Dumbbell Triceps Kickback", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 20u }, /* 108 */
    { "Incline Bench Dumbbell Triceps Kickback", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 20u }, /* 109 */
    { "Cable Triceps Kickback", EX_MUSCLE_ARMS, EX_EQUIPMENT_CABLE, 28u }, /* 110 */
    { "Cable Triceps Kickback from High Pulley", EX_MUSCLE_ARMS, EX_EQUIPMENT_CABLE, 26u }, /* 111 */
    { "Cable Glute Kickback", EX_MUSCLE_GLUTES, EX_EQUIPMENT_CABLE, 20u }, /* 112 */
    { "Glute Kickback Machine", EX_MUSCLE_GLUTES, EX_EQUIPMENT_PLATE_MACHINE, 45u }, /* 113 */
    { "Banded Glute Kickback", EX_MUSCLE_GLUTES, EX_EQUIPMENT_RESISTANCE_BAND, 12u }, /* 114 */
    { "Bodyweight Quadruped Glute Kickback", EX_MUSCLE_GLUTES, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 115 */
    { "Standing Bodyweight Glute Kickback", EX_MUSCLE_GLUTES, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 116 */
    { "Concentration Biceps", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 22u }, /* 117 */
    { "Dumbbell Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_DUMBBELL, 35u }, /* 118 */
    { "Decline Dumbbell Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_DUMBBELL, 32u }, /* 119 */
    { "Close-Grip Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_BARBELL, 90u }, /* 120 */
    { "Arnold Press", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 22u }, /* 121 */
    { "Push Press", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_BARBELL, 55u }, /* 122 */
    { "Chin-Up", EX_MUSCLE_BACK, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 123 */
    { "Straight-Arm Pulldown", EX_MUSCLE_BACK, EX_EQUIPMENT_CABLE, 30u }, /* 124 */
    { "Dumbbell Romanian Deadlift", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 50u }, /* 125 */
    { "Trap Bar Deadlift", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 145u }, /* 126 */
    { "Rack Pull", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 130u }, /* 127 */
    { "Front Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 85u }, /* 128 */
    { "Walking Lunge", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 30u }, /* 129 */
    { "Forward Lunge", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 30u }, /* 130 */
    { "Wall Sit", EX_MUSCLE_LEGS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 131 */
    { "Pistol Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 132 */
    { "Nordic Hamstring Curl", EX_MUSCLE_LEGS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 133 */
    { "Glute-Ham Raise", EX_MUSCLE_LEGS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 134 */
    { "Pendlay Row", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 85u }, /* 135 */
    { "Inverted Row", EX_MUSCLE_BACK, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 136 */
    { "Barbell Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_BARBELL, 42u }, /* 137 */
    { "EZ Bar Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_BARBELL, 40u }, /* 138 */
    { "Incline Dumbbell Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 18u }, /* 139 */
    { "Zottman Curl", EX_MUSCLE_ARMS, EX_EQUIPMENT_DUMBBELL, 20u }, /* 140 */
    { "Cable Overhead Tricep Extension", EX_MUSCLE_ARMS, EX_EQUIPMENT_CABLE, 28u }, /* 141 */
    { "Diamond Push-Up", EX_MUSCLE_CHEST, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 142 */
    { "Bench Dip", EX_MUSCLE_ARMS, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 143 */
    { "Lying Leg Raise", EX_MUSCLE_ABDOMEN, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 144 */
    { "Dead Bug", EX_MUSCLE_CORE, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 145 */
    { "Side Plank", EX_MUSCLE_CORE, EX_EQUIPMENT_BODYWEIGHT, 0u }, /* 146 */
    { "Cable Woodchopper", EX_MUSCLE_CORE, EX_EQUIPMENT_CABLE, 35u }, /* 147 */
    { "Bent-Over Dumbbell Rear Delt Fly", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 12u }, /* 148 */
    { "Barbell Shrug", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_BARBELL, 85u }, /* 149 */
    { "Power Clean", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 85u }, /* 150 */
    { "Clean and Press", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 65u }, /* 151 */
    { "Hang Clean", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 60u }, /* 152 */
    { "Power Snatch", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 55u }, /* 153 */
    { "Hang Snatch", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 50u }, /* 154 */
    { "Squat Clean", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 75u }, /* 155 */
    { "Squat Snatch", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 60u }, /* 156 */
    { "Push Jerk", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 70u }, /* 157 */
    { "Split Jerk", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 75u }, /* 158 */
    { "Thruster", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 50u }, /* 159 */
    { "Overhead Squat", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 50u }, /* 160 */
    { "Snatch Balance", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 50u }, /* 161 */
    { "Muscle Snatch", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 45u }, /* 162 */
    { "Clean Pull", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 110u }, /* 163 */
    { "Snatch Pull", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 90u }, /* 164 */
    { "High Pull", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_BARBELL, 60u }, /* 165 */
    { "Pause Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 90u }, /* 166 */
    { "Pin Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 100u }, /* 167 */
    { "Box Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 95u }, /* 168 */
    { "Safety Bar Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_BARBELL, 100u }, /* 169 */
    { "Pause Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_BARBELL, 85u }, /* 170 */
    { "Floor Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_BARBELL, 85u }, /* 171 */
    { "Deficit Deadlift", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 90u }, /* 172 */
    { "Block Pull", EX_MUSCLE_BACK, EX_EQUIPMENT_BARBELL, 160u }, /* 173 */
    { "One Arm Kettlebell Snatch", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_KETTLEBELL, 35u }, /* 174 */
    { "Kettlebell Clean and Press", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_KETTLEBELL, 40u }, /* 175 */
    { "Dumbbell Snatch", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_DUMBBELL, 30u }, /* 176 */
    { "Single Arm Dumbbell Press", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 25u }, /* 177 */
    { "Dumbbell Step-Up", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 35u }, /* 178 */
    { "Single Leg Romanian Deadlift", EX_MUSCLE_LEGS, EX_EQUIPMENT_DUMBBELL, 35u }, /* 179 */
    { "Renegade Row", EX_MUSCLE_BACK, EX_EQUIPMENT_DUMBBELL, 25u }, /* 180 */
    { "Dumbbell Thruster", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_DUMBBELL, 25u }, /* 181 */
    { "Waiter's Carry", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_DUMBBELL, 20u }, /* 182 */
    { "Suitcase Carry", EX_MUSCLE_CORE, EX_EQUIPMENT_DUMBBELL, 30u }, /* 183 */
    { "Seated Chest Press Machine", EX_MUSCLE_CHEST, EX_EQUIPMENT_PLATE_MACHINE, 90u }, /* 184 */
    { "Flat Dumbbell Bench Press", EX_MUSCLE_CHEST, EX_EQUIPMENT_DUMBBELL, 30u }, /* 185 */
    { "Hip Thrust Machine", EX_MUSCLE_GLUTES, EX_EQUIPMENT_PLATE_MACHINE, 140u }, /* 186 */
    { "Unilateral Leg Extension Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 50u }, /* 187 */
    { "Unilateral Leg Curl Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 40u }, /* 188 */
    { "Oblique Crunch Machine", EX_MUSCLE_CORE, EX_EQUIPMENT_PLATE_MACHINE, 40u }, /* 189 */
    { "Unilateral Row Machine", EX_MUSCLE_BACK, EX_EQUIPMENT_PLATE_MACHINE, 75u }, /* 190 */
    { "Unilateral High Row Machine", EX_MUSCLE_BACK, EX_EQUIPMENT_PLATE_MACHINE, 75u }, /* 191 */
    { "Unilateral Shoulder Press Machine", EX_MUSCLE_SHOULDERS, EX_EQUIPMENT_PLATE_MACHINE, 55u }, /* 192 */
    { "Belt Squat Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_PLATE_MACHINE, 150u }, /* 193 */
    { "Hamstring Curl Machine", EX_MUSCLE_LEGS, EX_EQUIPMENT_CABLE, 50u }, /* 194 */
    { "Treadmill", EX_MUSCLE_LEGS, EX_EQUIPMENT_CARDIO, 0u }, /* 195 */
    { "Medicine Ball Slam", EX_MUSCLE_FULL_BODY, EX_EQUIPMENT_MEDICINE_BALL, 0u }, /* 196 */
    { "Swiss Ball Crunch", EX_MUSCLE_CORE, EX_EQUIPMENT_OTHER, 0u }, /* 197 */
    { "Bosu Ball Squat", EX_MUSCLE_LEGS, EX_EQUIPMENT_OTHER, 0u }, /* 198 */
};
