/* Auto-generated by gameboy/tools/gen-foundation-foods.mjs — do not edit by hand. */
/* Source: data/usda_foundation_foods.json. */
#ifndef FOUNDATION_FOODS_H
#define FOUNDATION_FOODS_H

#include <stdint.h>

/* One USDA Foundation Food, all values per 100 g.
 * Macros are decigrams (0.1 g resolution); energy is whole kcal. */
typedef struct {
    const char *name;
    uint16_t kcal;        /* energy, kcal */
    uint16_t protein_dg;  /* protein, decigrams (0.1 g) */
    uint16_t fat_dg;      /* total fat, decigrams (0.1 g) */
    uint16_t carbs_dg;    /* carbohydrate by difference, decigrams (0.1 g) */
} foundation_food_t;

#define FOUNDATION_FOOD_COUNT 225u

/* The table and its name strings live in this ROM bank. Callers must
 * SWITCH_ROM(FOUNDATION_FOODS_BANK) before dereferencing the array. */
#define FOUNDATION_FOODS_BANK 2

extern const foundation_food_t foundation_foods[FOUNDATION_FOOD_COUNT];

#endif /* FOUNDATION_FOODS_H */
