export const AREA_TOOLTIP_WIDTH = 120;
export const AREA_TOOLTIP_HEIGHT = 56;

export const MULTIPLE_LINES_CALLOUT_WIDTH = 44;
export const MULTIPLE_LINES_CALLOUT_HEIGHT = 28;
export const MULTIPLE_LINES_TOOLTIP_WIDTH = 120;
export const MULTIPLE_LINES_TOOLTIP_HEIGHT = 56;

export const STACKED_BAR_TOOLTIP_WIDTH = 90;
export const STACKED_BAR_TOOLTIP_HEIGHT = 36;

export const TRAINING_CONSISTENCY_TOOLTIP_WIDTH = 100;
export const TRAINING_CONSISTENCY_TOOLTIP_HEIGHT = 40;
