export type AvatarIcon =
  | 'person'
  | 'fitness_center'
  | 'bolt'
  | 'monitoring'
  | 'directions_run'
  | 'sports'
  | 'emoji_events'
  | 'heart'
  | 'flame'
  | 'meditation'
  | 'restaurant'
  | 'ramen-dining'
  | 'dinner-dining'
  | 'bakery-dining'
  | 'local-cafe'
  | 'nutrition';
