/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/food/{fdcId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetches details for one food item by FDC ID
     * @description Retrieves a single food item by an FDC ID. Optional format and nutrients can be specified.
     */
    get: operations['getFood'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/foods': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetches details for multiple food items using input FDC IDs
     * @description Retrieves a list of food items by a list of up to 20 FDC IDs. Optional format and nutrients can be specified. Invalid FDC ID's or ones that are not found are omitted and an empty set is returned if there are no matches.
     */
    get: operations['getFoods'];
    put?: never;
    /**
     * Fetches details for multiple food items using input FDC IDs
     * @description Retrieves a list of food items by a list of up to 20 FDC IDs. Optional format and nutrients can be specified. Invalid FDC ID's or ones that are not found are omitted and an empty set is returned if there are no matches.
     */
    post: operations['postFoods'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/foods/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a paged list of foods, in the 'abridged' format
     * @description Retrieves a paged list of foods. Use the pageNumber parameter to page through the entire result set.
     */
    get: operations['getFoodsList'];
    put?: never;
    /**
     * Returns a paged list of foods, in the 'abridged' format
     * @description Retrieves a paged list of foods. Use the pageNumber parameter to page through the entire result set.
     */
    post: operations['postFoodsList'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/foods/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns a list of foods that matched search (query) keywords
     * @description Search for foods using keywords. Results can be filtered by dataType and there are options for result page sizes or sorting.
     */
    get: operations['getFoodsSearch'];
    put?: never;
    /**
     * Returns a list of foods that matched search (query) keywords
     * @description Search for foods using keywords. Results can be filtered by dataType and there are options for result page sizes or sorting.
     */
    post: operations['postFoodsSearch'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/json-spec': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns this documentation in JSON format
     * @description The OpenAPI 3.0 specification for the FDC API rendered as JSON (JavaScript Object Notation)
     */
    get: operations['getJsonSpec'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/yaml-spec': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns this documentation in JSON format
     * @description The OpenAPI 3.0 specification for the FDC API rendered as YAML (YAML Ain't Markup Language)
     */
    get: operations['getYamlSpec'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AbridgedFoodItem: {
      /** @example Branded */
      dataType: string;
      /** @example NUT 'N BERRY MIX */
      description: string;
      /** @example 534358 */
      fdcId: number;
      foodNutrients?: components['schemas']['AbridgedFoodNutrient'][];
      /** @example 4/1/2019 */
      publicationDate?: string;
      /**
       * @description only applies to Branded Foods
       * @example Kar Nut Products Company
       */
      brandOwner?: string;
      /**
       * @description only applies to Branded Foods
       * @example 077034085228
       */
      gtinUpc?: string;
      /**
       * @description only applies to Foundation and SRLegacy Foods
       * @example 7954
       */
      ndbNumber?: string;
      /**
       * @description only applies to Survey Foods
       * @example 27415110
       */
      foodCode?: string;
    };
    BrandedFoodItem: {
      /** @example 534358 */
      fdcId: number;
      /** @example 8/18/2018 */
      availableDate?: string;
      /** @example Kar Nut Products Company */
      brandOwner?: string;
      /** @example LI */
      dataSource?: string;
      /** @example Branded */
      dataType: string;
      /** @example NUT 'N BERRY MIX */
      description: string;
      /** @example Branded */
      foodClass?: string;
      /** @example 077034085228 */
      gtinUpc?: string;
      /** @example 1 ONZ */
      householdServingFullText?: string;
      /** @example PEANUTS (PEANUTS, PEANUT AND/OR SUNFLOWER OIL). RAISINS. DRIED CRANBERRIES (CRANBERRIES, SUGAR, SUNFLOWER OIL). SUNFLOWER KERNELS AND ALMONDS (SUNFLOWER KERNELS AND ALMONDS, PEANUT AND/OR SUNFLOWER OIL). */
      ingredients?: string;
      /** @example 8/18/2018 */
      modifiedDate?: string;
      /** @example 4/1/2019 */
      publicationDate?: string;
      /**
       * Format: float32
       * @example 28
       */
      servingSize?: number;
      /** @example g */
      servingSizeUnit?: string;
      /** @example Popcorn, Peanuts, Seeds & Related Snacks */
      brandedFoodCategory?: string;
      foodNutrients?: components['schemas']['FoodNutrient'][];
      foodUpdateLog?: components['schemas']['FoodUpdateLog'][];
      labelNutrients?: {
        fat?: {
          /**
           * Format: float
           * @example 8.9992
           */
          value?: number;
        };
        saturatedFat?: {
          /**
           * Format: float
           * @example 0.9996
           */
          value?: number;
        };
        transFat?: {
          /**
           * Format: float
           * @example 0
           */
          value?: number;
        };
        cholesterol?: {
          /**
           * Format: float
           * @example 0
           */
          value?: number;
        };
        sodium?: {
          /**
           * Format: float
           * @example 0
           */
          value?: number;
        };
        carbohydrates?: {
          /**
           * Format: float
           * @example 12.0008
           */
          value?: number;
        };
        fiber?: {
          /**
           * Format: float
           * @example 1.988
           */
          value?: number;
        };
        sugars?: {
          /**
           * Format: float
           * @example 7.9996
           */
          value?: number;
        };
        protein?: {
          /**
           * Format: float
           * @example 4.0012
           */
          value?: number;
        };
        calcium?: {
          /**
           * Format: float
           * @example 19.88
           */
          value?: number;
        };
        iron?: {
          /**
           * Format: float
           * @example 0.7196
           */
          value?: number;
        };
        postassium?: {
          /**
           * Format: float
           * @example 159.88
           */
          value?: number;
        };
        calories?: {
          /**
           * Format: float
           * @example 140
           */
          value?: number;
        };
      };
    };
    FoundationFoodItem: {
      /** @example 747448 */
      fdcId: number;
      /** @example Foundation */
      dataType: string;
      /** @example Strawberries, raw */
      description: string;
      /** @example FinalFood */
      foodClass?: string;
      /** @example Source number reflects the actual number of samples analyzed for a nutrient. Repeat nutrient analyses may have been done on the same sample with the values shown. */
      footNote?: string;
      /** @example false */
      isHistoricalReference?: boolean;
      /** @example 9316 */
      ndbNumber?: string;
      /** @example 12/16/2019 */
      publicationDate?: string;
      /** @example Fragaria X ananassa */
      scientificName?: string;
      foodCategory?: components['schemas']['FoodCategory'];
      foodComponents?: components['schemas']['FoodComponent'][];
      foodNutrients?: components['schemas']['FoodNutrient'][];
      foodPortions?: components['schemas']['FoodPortion'][];
      inputFoods?: components['schemas']['InputFoodFoundation'][];
      nutrientConversionFactors?: components['schemas']['NutrientConversionFactors'][];
    };
    SRLegacyFoodItem: {
      /** @example 170379 */
      fdcId: number;
      /** @example SR Legacy */
      dataType: string;
      /** @example Broccoli, raw */
      description: string;
      /** @example FinalFood */
      foodClass?: string;
      /** @example true */
      isHistoricalReference?: boolean;
      /** @example 11090 */
      ndbNumber?: string;
      /** @example 4/1/2019 */
      publicationDate?: string;
      /** @example Brassica oleracea var. italica */
      scientificName?: string;
      foodCategory?: components['schemas']['FoodCategory'];
      foodNutrients?: components['schemas']['FoodNutrient'][];
      nutrientConversionFactors?: components['schemas']['NutrientConversionFactors'][];
    };
    SurveyFoodItem: {
      /** @example 337985 */
      fdcId: number;
      /** @example Survey (FNDDS) */
      datatype?: string;
      /** @example Beef curry */
      description: string;
      /** @example 12/31/2014 */
      endDate?: string;
      /** @example Survey */
      foodClass?: string;
      /** @example 27116100 */
      foodCode?: string;
      /** @example 4/1/2019 */
      publicationDate?: string;
      /** @example 1/1/2013 */
      startDate?: string;
      foodAttributes?: components['schemas']['FoodAttribute'][];
      foodPortions?: components['schemas']['FoodPortion'][];
      inputFoods?: components['schemas']['InputFoodSurvey'][];
      wweiaFoodCategory?: components['schemas']['WweiaFoodCategory'];
    };
    SampleFoodItem: {
      /** @example 45551 */
      fdcId: number;
      /** @example Sample */
      datatype?: string;
      /** @example Beef, Tenderloin Roast, select, roasted, comp5, lean (34BLTR) */
      description: string;
      /** @example Composite */
      foodClass?: string;
      /** @example 4/1/2019 */
      publicationDate?: string;
      foodAttributes?: components['schemas']['FoodCategory'][];
    };
    AbridgedFoodNutrient: {
      /**
       * Format: uint
       * @example 303
       */
      number?: number;
      /** @example Iron, Fe */
      name?: string;
      /**
       * Format: float
       * @example 0.53
       */
      amount?: number;
      /** @example mg */
      unitName?: string;
      /** @example LCCD */
      derivationCode?: string;
      /** @example Calculated from a daily value percentage per serving size measure */
      derivationDescription?: string;
    };
    FoodNutrient: {
      /**
       * Format: uint
       * @example 167514
       */
      id: number;
      /**
       * Format: float
       * @example 0
       */
      amount?: number;
      /**
       * Format: int32
       * @example 49
       */
      dataPoints?: number;
      /**
       * Format: float
       * @example 73.73
       */
      min?: number;
      /**
       * Format: float
       * @example 91.8
       */
      max?: number;
      /**
       * Format: float
       * @example 90.3
       */
      median?: number;
      /** @example FoodNutrient */
      type?: string;
      nutrient?: components['schemas']['Nutrient'];
      foodNutrientDerivation?: components['schemas']['FoodNutrientDerivation'];
      nutrientAnalysisDetails?: components['schemas']['NutrientAnalysisDetails'];
    };
    /** @description a food nutrient */
    Nutrient: {
      /**
       * Format: uint
       * @example 1005
       */
      id?: number;
      /** @example 305 */
      number?: string;
      /** @example Carbohydrate, by difference */
      name?: string;
      /**
       * Format: uint
       * @example 1110
       */
      rank?: number;
      /** @example g */
      unitName?: string;
    };
    FoodNutrientDerivation: {
      /**
       * Format: int32
       * @example 75
       */
      id?: number;
      /** @example LCCD */
      code?: string;
      /** @example Calculated from a daily value percentage per serving size measure */
      description?: string;
      foodNutrientSource?: components['schemas']['FoodNutrientSource'];
    };
    FoodNutrientSource: {
      /**
       * Format: int32
       * @example 9
       */
      id?: number;
      /** @example 12 */
      code?: string;
      /** @example Manufacturer's analytical; partial documentation */
      description?: string;
    };
    NutrientAnalysisDetails: {
      /** @example 343866 */
      subSampleId?: number;
      /**
       * Format: float
       * @example 0
       */
      amount?: number;
      /** @example 1005 */
      nutrientId?: number;
      /** @example 10.2135/cropsci2017.04.0244 */
      labMethodDescription?: string;
      labMethodOriginalDescription?: string;
      /**
       * Format: url
       * @example https://doi.org/10.2135/cropsci2017.04.0244
       */
      labMethodLink?: string;
      /** @example DOI for Beans */
      labMethodTechnique?: string;
      nutrientAcquisitionDetails?: components['schemas']['NutrientAcquisitionDetails'][];
    };
    NutrientAcquisitionDetails: {
      /** @example 321632 */
      sampleUnitId?: number;
      /** @example 12/2/2005 */
      purchaseDate?: string;
      /** @example TRUSSVILLE */
      storeCity?: string;
      /** @example AL */
      storeState?: string;
    };
    NutrientConversionFactors: {
      /** @example .ProteinConversionFactor */
      type?: string;
      /**
       * Format: float
       * @example 6.25
       */
      value?: number;
    };
    FoodUpdateLog: {
      /** @example 534358 */
      fdcId?: number;
      /** @example 8/18/2018 */
      availableDate?: string;
      /** @example Kar Nut Products Company */
      brandOwner?: string;
      /** @example LI */
      dataSource?: string;
      /** @example Branded */
      dataType?: string;
      /** @example NUT 'N BERRY MIX */
      description?: string;
      /** @example Branded */
      foodClass?: string;
      /** @example 077034085228 */
      gtinUpc?: string;
      /** @example 1 ONZ */
      householdServingFullText?: string;
      /** @example PEANUTS (PEANUTS, PEANUT AND/OR SUNFLOWER OIL). RAISINS. DRIED CRANBERRIES (CRANBERRIES, SUGAR, SUNFLOWER OIL). SUNFLOWER KERNELS AND ALMONDS (SUNFLOWER KERNELS AND ALMONDS, PEANUT AND/OR SUNFLOWER OIL). */
      ingredients?: string;
      /** @example 8/18/2018 */
      modifiedDate?: string;
      /** @example 4/1/2019 */
      publicationDate?: string;
      /**
       * Format: float32
       * @example 28
       */
      servingSize?: number;
      /** @example g */
      servingSizeUnit?: string;
      /** @example Popcorn, Peanuts, Seeds & Related Snacks */
      brandedFoodCategory?: string;
      /** @example Nutrient Added, Nutrient Updated */
      changes?: string;
      foodAttributes?: components['schemas']['FoodAttribute'][];
    };
    FoodAttribute: {
      /** @example 25117 */
      id?: number;
      /** @example 1 */
      sequenceNumber?: number;
      /** @example Moisture change: -5.0% */
      value?: string;
      FoodAttributeType?: {
        /** @example 1002 */
        id?: number;
        /** @example Adjustments */
        name?: string;
        /** @example Adjustments made to foods, including moisture and fat changes. */
        description?: string;
      };
    };
    FoodCategory: {
      /**
       * Format: int32
       * @example 11
       */
      id?: number;
      /** @example 1100 */
      code?: string;
      /** @example Vegetables and Vegetable Products */
      description?: string;
    };
    FoodComponent: {
      /**
       * Format: int32
       * @example 59929
       */
      id?: number;
      /** @example External fat */
      name?: string;
      /** @example 24 */
      dataPoints?: number;
      /** @example 2.1 */
      gramWeight?: number;
      /** @example true */
      isRefuse?: boolean;
      /** @example 2011 */
      minYearAcquired?: number;
      /** @example 0.5 */
      percentWeight?: number;
    };
    FoodPortion: {
      /**
       * Format: int32
       * @example 135806
       */
      id?: number;
      /**
       * Format: float
       * @example 1
       */
      amount?: number;
      /**
       * Format: int32
       * @example 9
       */
      dataPoints?: number;
      /**
       * Format: float
       * @example 91
       */
      gramWeight?: number;
      /** @example 2011 */
      minYearAcquired?: number;
      /** @example 10205 */
      modifier?: string;
      /** @example 1 cup */
      portionDescription?: string;
      /** @example 1 */
      sequenceNumber?: number;
      measureUnit?: components['schemas']['MeasureUnit'];
    };
    /** @description applies to Foundation foods. Not all inputFoods will have all fields. */
    InputFoodFoundation: {
      /** @example 45551 */
      id?: number;
      /** @example Beef, Tenderloin Roast, select, roasted, comp5, lean (34BLTR) */
      foodDescription?: string;
      inputFood?: components['schemas']['SampleFoodItem'];
    };
    /** @description applies to Survey (FNDDS). Not all inputFoods will have all fields. */
    InputFoodSurvey: {
      /** @example 18146 */
      id?: number;
      /**
       * Format: float
       * @example 1.5
       */
      amount?: number;
      /** @example Spices, curry powder */
      foodDescription?: string;
      /** @example 2015 */
      ingredientCode?: number;
      /** @example Spices, curry powder */
      ingredientDescription?: string;
      /**
       * Format: float
       * @example 9.45
       */
      ingredientWeight?: number;
      /** @example 21000 */
      portionCode?: string;
      /** @example 1 tablespoon */
      portionDescription?: string;
      /** @example 6 */
      sequenceNumber?: number;
      /** @example 0 */
      surveyFlag?: number;
      /** @example TB */
      unit?: string;
      inputFood?: components['schemas']['SurveyFoodItem'];
      retentionFactor?: components['schemas']['RetentionFactor'];
    };
    MeasureUnit: {
      /**
       * Format: int32
       * @example 999
       */
      id?: number;
      /** @example undetermined */
      abbreviation?: string;
      /** @example undetermined */
      name?: string;
    };
    RetentionFactor: {
      /** @example 235 */
      id?: number;
      /** @example 3460 */
      code?: number;
      /** @example VEG, ROOTS, ETC, SAUTEED */
      description?: string;
    };
    WweiaFoodCategory: {
      /** @example 3002 */
      wweiaFoodCategoryCode?: number;
      /** @example Meat mixed dishes */
      wweiaFoodCategoryDescription?: string;
    };
    /** @description JSON for request body of 'foods' POST request. Retrieves a list of food items by a list of up to 20 FDC IDs. Optional format and nutrients can be specified. Invalid FDC ID's or ones that are not found are omitted and an empty set is returned if there are no matches. */
    FoodsCriteria: {
      /**
       * @description List of multiple FDC ID's
       * @example [
       *       534358,
       *       373052,
       *       616350
       *     ]
       */
      fdcIds?: number[];
      /**
       * @description Optional. 'abridged' for an abridged set of elements, 'full' for all elements (default).
       * @enum {string}
       */
      format?: 'abridged' | 'full';
      /**
       * @description Optional. List of up to 25 nutrient numbers. Only the nutrient information for the specified nutrients will be returned.  If a food does not have any matching nutrients, the food will be returned with an empty foodNutrients element.
       * @example [
       *       203,
       *       204,
       *       205
       *     ]
       */
      nutrients?: number[];
    };
    /** @description JSON for request body of 'list' POST request */
    FoodListCriteria: {
      /**
       * @description Optional. Filter on a specific data type; specify one or more values in an array.
       * @example [
       *       "Foundation",
       *       "SR Legacy"
       *     ]
       */
      dataType?: ('Branded' | 'Foundation' | 'Survey (FNDDS)' | 'SR Legacy')[];
      /**
       * @description Optional. Maximum number of results to return for the current page. Default is 50.
       * @example 25
       */
      pageSize?: number;
      /**
       * @description Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
       * @example 2
       */
      pageNumber?: number;
      /**
       * @description Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
       * @enum {string}
       */
      sortBy?: 'dataType.keyword' | 'lowercaseDescription.keyword' | 'fdcId' | 'publishedDate';
      /**
       * @description Optional. The sort direction for the results. Only applicable if sortBy is specified.
       * @enum {string}
       */
      sortOrder?: 'asc' | 'desc';
    };
    /** @description JSON for request body of 'search' POST request */
    FoodSearchCriteria: {
      /**
       * @description Search terms to use in the search. The string may also include standard [search operators](https://fdc.nal.usda.gov/help.html#bkmk-2)
       * @example Cheddar cheese
       */
      query?: string;
      /**
       * @description Optional. Filter on a specific data type; specify one or more values in an array.
       * @example [
       *       "Foundation",
       *       "SR Legacy"
       *     ]
       */
      dataType?: ('Branded' | 'Foundation' | 'Survey (FNDDS)' | 'SR Legacy')[];
      /**
       * @description Optional. Maximum number of results to return for the current page. Default is 50.
       * @example 25
       */
      pageSize?: number;
      /**
       * @description Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
       * @example 2
       */
      pageNumber?: number;
      /**
       * @description Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
       * @enum {string}
       */
      sortBy?: 'dataType.keyword' | 'lowercaseDescription.keyword' | 'fdcId' | 'publishedDate';
      /**
       * @description Optional. The sort direction for the results. Only applicable if sortBy is specified.
       * @enum {string}
       */
      sortOrder?: 'asc' | 'desc';
      /**
       * @description Optional. Filter results based on the brand owner of the food. Only applies to Branded Foods.
       * @example Kar Nut Products Company
       */
      brandOwner?: string;
    };
    SearchResult: {
      /** @description A copy of the criteria that were used in the search. */
      foodSearchCriteria?: Record<string, never>;
      /**
       * @description The total number of foods found matching the search criteria.
       * @example 1034
       */
      totalHits?: number;
      /** @description The current page of results being returned. */
      currentPage?: number;
      /** @description The total number of pages found matching the search criteria. */
      totalPages?: number;
      /** @description The list of foods found matching the search criteria. See Food Fields below. */
      foods?: components['schemas']['SearchResultFood'][];
    };
    SearchResultFood: {
      /**
       * @description Unique ID of the food.
       * @example 45001529
       */
      fdcId: number;
      /**
       * @description The type of the food data.
       * @example Branded
       */
      dataType?: string;
      /**
       * @description The description of the food.
       * @example BROCCOLI
       */
      description: string;
      /** @description Any A unique ID identifying the food within FNDDS. */
      foodCode?: string;
      foodNutrients?: components['schemas']['AbridgedFoodNutrient'][];
      /**
       * @description Date the item was published to FDC.
       * @example 4/1/2019
       */
      publicationDate?: string;
      /** @description The scientific name of the food. */
      scientificName?: string;
      /**
       * @description Brand owner for the food. Only applies to Branded Foods.
       * @example Supervalu, Inc.
       */
      brandOwner?: string;
      /**
       * @description GTIN or UPC code identifying the food. Only applies to Branded Foods.
       * @example 041303020937
       */
      gtinUpc?: string;
      /** @description The list of ingredients (as it appears on the product label). Only applies to Branded Foods. */
      ingredients?: string;
      /** @description Unique number assigned for foundation foods. Only applies to Foundation and SRLegacy Foods. */
      ndbNumber?: string;
      /**
       * @description Any additional descriptions of the food.
       * @example Coon; sharp cheese; Tillamook; Hoop; Pioneer; New York; Wisconsin; Longhorn
       */
      additionalDescriptions?: string;
      /** @description allHighlightFields */
      allHighlightFields?: string;
      /**
       * Format: float
       * @description Relative score indicating how well the food matches the search criteria.
       */
      score?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getFood: {
    parameters: {
      query?: {
        /** @description Optional. 'abridged' for an abridged set of elements, 'full' for all elements (default). */
        format?: 'abridged' | 'full';
        /** @description Optional. List of up to 25 nutrient numbers. Only the nutrient information for the specified nutrients will be returned. Should be comma separated list (e.g. nutrients=203,204) or repeating parameters (e.g. nutrients=203&nutrients=204). If a food does not have any matching nutrients, the food will be returned with an empty foodNutrients element. */
        nutrients?: number[];
      };
      header?: never;
      path: {
        /** @description FDC id of the food to retrieve */
        fdcId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One food result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['AbridgedFoodItem']
            | components['schemas']['BrandedFoodItem']
            | components['schemas']['FoundationFoodItem']
            | components['schemas']['SRLegacyFoodItem']
            | components['schemas']['SurveyFoodItem'];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description no results found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getFoods: {
    parameters: {
      query: {
        /** @description List of multiple FDC ID's. Should be comma separated list (e.g. fdcIds=534358,373052) or repeating parameters (e.g. fdcIds=534358&fdcIds=373052). */
        fdcIds: string[];
        /** @description Optional. 'abridged' for an abridged set of elements, 'full' for all elements (default). */
        format?: 'abridged' | 'full';
        /** @description Optional. List of up to 25 nutrient numbers. Only the nutrient information for the specified nutrients will be returned. Should be comma separated list (e.g. nutrients=203,204) or repeating parameters (e.g. nutrients=203&nutrients=204). If a food does not have any matching nutrients, the food will be returned with an empty foodNutrients element. */
        nutrients?: number[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of Food details matching specified FDC ID's. Invalid FDC ID's or ones that are not found are omitted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': (
            | components['schemas']['AbridgedFoodItem']
            | components['schemas']['BrandedFoodItem']
            | components['schemas']['FoundationFoodItem']
            | components['schemas']['SRLegacyFoodItem']
            | components['schemas']['SurveyFoodItem']
          )[];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  postFoods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodsCriteria'];
      };
    };
    responses: {
      /** @description List of Food details matching specified FDC ID's. Invalid FDC ID's or ones that are not found are omitted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': (
            | components['schemas']['AbridgedFoodItem']
            | components['schemas']['BrandedFoodItem']
            | components['schemas']['FoundationFoodItem']
            | components['schemas']['SRLegacyFoodItem']
            | components['schemas']['SurveyFoodItem']
          )[];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getFoodsList: {
    parameters: {
      query?: {
        /**
         * @description Optional. Filter on a specific data type; specify one or more values in an array.
         * @example [
         *       "Foundation",
         *       "SR Legacy"
         *     ]
         */
        dataType?: ('Branded' | 'Foundation' | 'Survey (FNDDS)' | 'SR Legacy')[];
        /**
         * @description Optional. Maximum number of results to return for the current page. Default is 50.
         * @example 25
         */
        pageSize?: number;
        /** @description Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize) */
        pageNumber?: number;
        /** @description Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases. */
        sortBy?: 'dataType.keyword' | 'lowercaseDescription.keyword' | 'fdcId' | 'publishedDate';
        /** @description Optional. The sort direction for the results. Only applicable if sortBy is specified. */
        sortOrder?: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of foods for the requested page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AbridgedFoodItem'][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  postFoodsList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodListCriteria'];
      };
    };
    responses: {
      /** @description List of foods for the requested page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AbridgedFoodItem'][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getFoodsSearch: {
    parameters: {
      query: {
        /**
         * @description One or more search terms.  The string may include [search operators](https://fdc.nal.usda.gov/help.html#bkmk-2)
         * @example cheddar cheese
         */
        query: string;
        /**
         * @description Optional. Filter on a specific data type; specify one or more values in an array.
         * @example [
         *       "Foundation",
         *       "SR Legacy"
         *     ]
         */
        dataType?: ('Branded' | 'Foundation' | 'Survey (FNDDS)' | 'SR Legacy')[];
        /**
         * @description Optional. Maximum number of results to return for the current page. Default is 50.
         * @example 25
         */
        pageSize?: number;
        /** @description Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize) */
        pageNumber?: number;
        /**
         * @description Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
         * @example description
         */
        sortBy?: 'dataType.keyword' | 'lowercaseDescription.keyword' | 'fdcId' | 'publishedDate';
        /**
         * @description Optional. The sort direction for the results. Only applicable if sortBy is specified.
         * @example asc
         */
        sortOrder?: 'asc' | 'desc';
        /**
         * @description Optional. Filter results based on the brand owner of the food. Only applies to Branded Foods
         * @example Kar Nut Products Company
         */
        brandOwner?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of foods that matched search terms */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchResult'][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  postFoodsSearch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The query string may also include standard [search operators](https://fdc.nal.usda.gov/help.html#bkmk-2) */
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodSearchCriteria'];
      };
    };
    responses: {
      /** @description List of foods that matched search terms */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchResult'][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getJsonSpec: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON rendering of OpenAPI 3.0 specification */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getYamlSpec: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description YAML rendering of OpenAPI 3.0 specification */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
