function periodTable(symbol, values) {
  const rows = [];
  for (let i = 0; i < values.length; i += 8) {
    rows.push(
      '    ' +
        values
          .slice(i, i + 8)
          .map((value) => `${value}u`)
          .join(', ') +
        ','
    );
  }
  return `const uint16_t ${symbol}[MUSIC_NOTE_COUNT] = {\n${rows.join('\n')}\n};\n`;
}

function eventTable(events) {
  const rows = [];
  for (let i = 0; i < events.length; i += 6) {
    rows.push(
      '    ' +
        events
          .slice(i, i + 6)
          .map(([delta, target, value]) => `{${delta}u,${target}u,${value}u}`)
          .join(', ') +
        ','
    );
  }
  return `const MusicEvent music_events[MUSIC_EVENT_COUNT] = {\n${rows.join('\n')}\n};\n`;
}

export function musicHeader({ audioBank, sfx, sfxFrames, sfxFile, song, songFile }) {
  return `/* Auto-generated by gameboy/tools/gen-music.mjs — do not edit by hand. */
/* Sources: gameboy/assets/${sfxFile}, gameboy/assets/${songFile}. */
#ifndef MUSCLOG_MUSIC_DATA_H
#define MUSCLOG_MUSIC_DATA_H

#include <stdint.h>

/* The audio runtime (audio.c) and these tables share this ROM bank. */
#define AUDIO_BANK ${audioBank}

/* UI confirm/select blip: a single pulse note (from ${sfxFile}). */
#define MUSIC_SFX_PERIOD ${sfx.period}u   /* 11-bit pulse period (MIDI note ${sfx.note}) */
#define MUSIC_SFX_FRAMES ${sfxFrames}u

/* One step of the soundtrack event stream. The player applies the event, then
 * waits \`delta_frames\` video frames before the next one ("wait-after"). target
 * 0 = lead (pulse 2), 1 = bass (wave 3), 2 = drum (noise 4), 255 = NOP (carries a
 * long gap). For lead/bass, \`value\` is a 1-based index into the period tables
 * (0 = note off); for drums it is 1 = kick, 2 = snare. */
typedef struct {
    uint8_t delta_frames;
    uint8_t target;
    uint8_t value;
} MusicEvent;

#define MUSIC_TARGET_LEAD 0u
#define MUSIC_TARGET_BASS 1u
#define MUSIC_TARGET_DRUM 2u
#define MUSIC_TARGET_NOP  255u

#define MUSIC_DRUM_KICK  1u
#define MUSIC_DRUM_SNARE 2u

#define MUSIC_NOTE_COUNT ${song.noteList.length}u
#define MUSIC_EVENT_COUNT ${song.events.length}u

/* Events before this index are a play-once intro; when the stream ends the player
 * wraps here, so events from this index on loop forever (a self-similarity scan in
 * gen-music.mjs found the repeating section). 0 = the whole song loops. */
#define MUSIC_LOOP_INDEX ${song.loopIndex}u

/* Period lookups shared by lead and bass, indexed by an event's 1-based value-1. */
extern const uint16_t music_pulse_periods[MUSIC_NOTE_COUNT];
extern const uint16_t music_wave_periods[MUSIC_NOTE_COUNT];
extern const MusicEvent music_events[MUSIC_EVENT_COUNT];

#endif /* MUSCLOG_MUSIC_DATA_H */
`;
}

export function musicBody({ audioBank, song, sfxFile, songFile }) {
  return `/* Auto-generated by gameboy/tools/gen-music.mjs — do not edit by hand. */
/* Sources: gameboy/assets/${sfxFile}, gameboy/assets/${songFile}. */
#pragma bank ${audioBank}
#include "music_data.h"

${periodTable('music_pulse_periods', song.pulsePeriods)}
${periodTable('music_wave_periods', song.wavePeriods)}
${eventTable(song.events)}`;
}
