/**
 * The dispatcher is the one hand-written piece of the rep-counting model
 * directory — everything else there is generated by training-data/train.py.
 * These tests pin the two things a retrain must not silently change: which
 * model a mechanic type resolves to, and that forests stay lazily loaded.
 */
const mockGeneralClassifier = jest.fn((): [number, number] => [0.9, 0.1]);
const mockCompoundClassifier = jest.fn((): [number, number] => [0.2, 0.8]);
const mockLoadGeneral = jest.fn(() => mockGeneralClassifier);
const mockLoadCompound = jest.fn(() => mockCompoundClassifier);

// Stands in for the generated ./models.js in a build where `compound` earned a
// dedicated model and every other mechanic type did not.
jest.mock('../repCountingModel/models', () => ({
  MODEL_LOADERS: { compound: mockLoadCompound, general: mockLoadGeneral },
}));

type ClassifySegment = (input: number[], mechanicType?: string) => [number, number];

/** Fresh module instance, so the memoization cache starts empty each test. */
function loadDispatcher(): ClassifySegment {
  jest.resetModules();
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  return require('../repCountingModel').classifySegment as ClassifySegment;
}

beforeEach(() => {
  jest.clearAllMocks();
});

describe('classifySegment', () => {
  it('routes a mechanic type with a dedicated model to that model', () => {
    const classifySegment = loadDispatcher();

    expect(classifySegment([1, 2, 3], 'compound')).toEqual([0.2, 0.8]);
    expect(mockLoadGeneral).not.toHaveBeenCalled();
  });

  it.each([['isolation'], ['cardio'], ['powerlifting'], [''], ['   '], [undefined]])(
    'falls back to the general model for %p',
    (mechanicType) => {
      const classifySegment = loadDispatcher();

      expect(classifySegment([1, 2, 3], mechanicType)).toEqual([0.9, 0.1]);
      expect(mockLoadCompound).not.toHaveBeenCalled();
    }
  );

  it('matches the mechanic type case- and whitespace-insensitively', () => {
    const classifySegment = loadDispatcher();

    expect(classifySegment([1, 2, 3], '  CoMpOuNd ')).toEqual([0.2, 0.8]);
  });

  it('passes the feature vector to the classifier untouched', () => {
    const classifySegment = loadDispatcher();
    const features = [1, 2, 3];

    classifySegment(features, 'compound');

    expect(mockCompoundClassifier).toHaveBeenCalledWith(features);
  });

  it('loads no forest until a segment is actually classified', () => {
    loadDispatcher();

    expect(mockLoadGeneral).not.toHaveBeenCalled();
    expect(mockLoadCompound).not.toHaveBeenCalled();
  });

  it('loads each forest at most once, however many segments it scores', () => {
    const classifySegment = loadDispatcher();

    classifySegment([1], 'compound');
    classifySegment([2], 'compound');
    classifySegment([3], 'compound');

    expect(mockLoadCompound).toHaveBeenCalledTimes(1);
    expect(mockCompoundClassifier).toHaveBeenCalledTimes(3);
  });

  it('loads only the forests the session touches', () => {
    const classifySegment = loadDispatcher();

    classifySegment([1], 'compound');

    expect(mockLoadCompound).toHaveBeenCalledTimes(1);
    expect(mockLoadGeneral).not.toHaveBeenCalled();
  });
});
