/**
 * Auto-generated by train.py via m2cgen.
 * classifySegment(features)[1] > 0.5  →  is a real rep.
 * Input: 41-feature vector (see segmentAndScorePipeline.ts for order).
 */
export declare function classifySegment(input: number[]): [number, number];
