// ATTENTION: This file and locales/untranslated.json are generated by scripts/generateLangFile.js
// Do not edit this file manually. Changes will be overwritten.

import 'intl-pluralrules';

import { enUS as localeEnUS, ptBR as localePtBR, ru as localeRu } from 'date-fns/locale';
import * as Localization from 'expo-localization';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// en-us
import enUsAccessToken from './locales/en-us/access_token.json';
import enUsAddMeal from './locales/en-us/addMeal.json';
import enUsAi from './locales/en-us/ai.json';
import enUsBodyFat from './locales/en-us/body_fat.json';
import enUsBodyMetrics from './locales/en-us/bodyMetrics.json';
import enUsCamera from './locales/en-us/camera.json';
import enUsCoach from './locales/en-us/coach.json';
import enUsCommon from './locales/en-us/common.json';
import enUsCreateWorkout from './locales/en-us/createWorkout.json';
import enUsCurrentGoalsCard from './locales/en-us/currentGoalsCard.json';
import enUsCycle from './locales/en-us/cycle.json';
import enUsDailySummaryCard from './locales/en-us/dailySummaryCard.json';
import enUsDatePicker from './locales/en-us/datePicker.json';
import enUsEatingPhaseBadge from './locales/en-us/eatingPhaseBadge.json';
import enUsEditFitnessDetails from './locales/en-us/editFitnessDetails.json';
import enUsEditPersonalInfo from './locales/en-us/editPersonalInfo.json';
import enUsEditScreenInfo from './locales/en-us/editScreenInfo.json';
import enUsEditSetDetails from './locales/en-us/editSetDetails.json';
import enUsEmptyStates from './locales/en-us/emptyStates.json';
import enUsEndWorkout from './locales/en-us/endWorkout.json';
import enUsErrors from './locales/en-us/errors.json';
import enUsExercises from './locales/en-us/exercises.json';
import enUsExerciseTransition from './locales/en-us/exerciseTransition.json';
import enUsExpiresIn from './locales/en-us/expires_in.json';
import enUsFocus from './locales/en-us/focus.json';
import enUsFood from './locales/en-us/food.json';
import enUsFoodFoodPortions from './locales/en-us/food_food_portions.json';
import enUsFoodSearch from './locales/en-us/foodSearch.json';
import enUsFreeTraining from './locales/en-us/freeTraining.json';
import enUsGoalHistoryCard from './locales/en-us/goalHistoryCard.json';
import enUsGoalsManagement from './locales/en-us/goalsManagement.json';
import enUsHealthConnect from './locales/en-us/healthConnect.json';
import enUsHome from './locales/en-us/home.json';
import enUsLogSetPerformance from './locales/en-us/logSetPerformance.json';
import enUsMealFoods from './locales/en-us/meal_foods.json';
import enUsMeals from './locales/en-us/meals.json';
import enUsNotifications from './locales/en-us/notifications.json';
import enUsNutrition from './locales/en-us/nutrition.json';
import enUsNutritionLogs from './locales/en-us/nutrition_logs.json';
import enUsNutritionGoals from './locales/en-us/nutritionGoals.json';
import enUsOnboarding from './locales/en-us/onboarding.json';
import enUsOptionsSelector from './locales/en-us/optionsSelector.json';
import enUsPastWorkoutHistory from './locales/en-us/pastWorkoutHistory.json';
import enUsPortionSizes from './locales/en-us/portionSizes.json';
import enUsProfile from './locales/en-us/profile.json';
import enUsProgress from './locales/en-us/progress.json';
import enUsReplaceExercise from './locales/en-us/replaceExercise.json';
import enUsRestOver from './locales/en-us/restOver.json';
import enUsRestTimer from './locales/en-us/restTimer.json';
import enUsSessionFeedback from './locales/en-us/sessionFeedback.json';
import enUsSettings from './locales/en-us/settings.json';
import enUsSnackbar from './locales/en-us/snackbar.json';
import enUsStartWorkout from './locales/en-us/startWorkout.json';
import enUsTimePicker from './locales/en-us/timePicker.json';
import enUsTokenType from './locales/en-us/token_type.json';
import enUsUserMenu from './locales/en-us/userMenu.json';
import enUsWorkout from './locales/en-us/workout.json';
import enUsWorkoutLogSets from './locales/en-us/workout_log_sets.json';
import enUsWorkoutLogs from './locales/en-us/workout_logs.json';
import enUsWorkoutTemplateSets from './locales/en-us/workout_template_sets.json';
import enUsWorkoutDetail from './locales/en-us/workoutDetail.json';
import enUsWorkoutDetails from './locales/en-us/workoutDetails.json';
import enUsWorkoutHistory from './locales/en-us/workoutHistory.json';
import enUsWorkoutLog from './locales/en-us/workoutLog.json';
import enUsWorkoutOptions from './locales/en-us/workoutOptions.json';
import enUsWorkouts from './locales/en-us/workouts.json';
import enUsWorkoutSession from './locales/en-us/workoutSession.json';
import enUsWorkoutSummary from './locales/en-us/workoutSummary.json';
// pt-br
import ptBrAccessToken from './locales/pt-br/access_token.json';
import ptBrAddMeal from './locales/pt-br/addMeal.json';
import ptBrAi from './locales/pt-br/ai.json';
import ptBrBodyFat from './locales/pt-br/body_fat.json';
import ptBrBodyMetrics from './locales/pt-br/bodyMetrics.json';
import ptBrCamera from './locales/pt-br/camera.json';
import ptBrCoach from './locales/pt-br/coach.json';
import ptBrCommon from './locales/pt-br/common.json';
import ptBrCreateWorkout from './locales/pt-br/createWorkout.json';
import ptBrCurrentGoalsCard from './locales/pt-br/currentGoalsCard.json';
import ptBrCycle from './locales/pt-br/cycle.json';
import ptBrDailySummaryCard from './locales/pt-br/dailySummaryCard.json';
import ptBrDatePicker from './locales/pt-br/datePicker.json';
import ptBrEatingPhaseBadge from './locales/pt-br/eatingPhaseBadge.json';
import ptBrEditFitnessDetails from './locales/pt-br/editFitnessDetails.json';
import ptBrEditPersonalInfo from './locales/pt-br/editPersonalInfo.json';
import ptBrEditScreenInfo from './locales/pt-br/editScreenInfo.json';
import ptBrEditSetDetails from './locales/pt-br/editSetDetails.json';
import ptBrEmptyStates from './locales/pt-br/emptyStates.json';
import ptBrEndWorkout from './locales/pt-br/endWorkout.json';
import ptBrErrors from './locales/pt-br/errors.json';
import ptBrExercises from './locales/pt-br/exercises.json';
import ptBrExerciseTransition from './locales/pt-br/exerciseTransition.json';
import ptBrExpiresIn from './locales/pt-br/expires_in.json';
import ptBrFocus from './locales/pt-br/focus.json';
import ptBrFood from './locales/pt-br/food.json';
import ptBrFoodFoodPortions from './locales/pt-br/food_food_portions.json';
import ptBrFoodSearch from './locales/pt-br/foodSearch.json';
import ptBrFreeTraining from './locales/pt-br/freeTraining.json';
import ptBrGoalHistoryCard from './locales/pt-br/goalHistoryCard.json';
import ptBrGoalsManagement from './locales/pt-br/goalsManagement.json';
import ptBrHealthConnect from './locales/pt-br/healthConnect.json';
import ptBrHome from './locales/pt-br/home.json';
import ptBrLogSetPerformance from './locales/pt-br/logSetPerformance.json';
import ptBrMealFoods from './locales/pt-br/meal_foods.json';
import ptBrMeals from './locales/pt-br/meals.json';
import ptBrNotifications from './locales/pt-br/notifications.json';
import ptBrNutrition from './locales/pt-br/nutrition.json';
import ptBrNutritionLogs from './locales/pt-br/nutrition_logs.json';
import ptBrNutritionGoals from './locales/pt-br/nutritionGoals.json';
import ptBrOnboarding from './locales/pt-br/onboarding.json';
import ptBrOptionsSelector from './locales/pt-br/optionsSelector.json';
import ptBrPastWorkoutHistory from './locales/pt-br/pastWorkoutHistory.json';
import ptBrPortionSizes from './locales/pt-br/portionSizes.json';
import ptBrProfile from './locales/pt-br/profile.json';
import ptBrProgress from './locales/pt-br/progress.json';
import ptBrReplaceExercise from './locales/pt-br/replaceExercise.json';
import ptBrRestOver from './locales/pt-br/restOver.json';
import ptBrRestTimer from './locales/pt-br/restTimer.json';
import ptBrSessionFeedback from './locales/pt-br/sessionFeedback.json';
import ptBrSettings from './locales/pt-br/settings.json';
import ptBrSnackbar from './locales/pt-br/snackbar.json';
import ptBrStartWorkout from './locales/pt-br/startWorkout.json';
import ptBrTimePicker from './locales/pt-br/timePicker.json';
import ptBrTokenType from './locales/pt-br/token_type.json';
import ptBrUserMenu from './locales/pt-br/userMenu.json';
import ptBrWorkout from './locales/pt-br/workout.json';
import ptBrWorkoutLogSets from './locales/pt-br/workout_log_sets.json';
import ptBrWorkoutLogs from './locales/pt-br/workout_logs.json';
import ptBrWorkoutTemplateSets from './locales/pt-br/workout_template_sets.json';
import ptBrWorkoutDetail from './locales/pt-br/workoutDetail.json';
import ptBrWorkoutDetails from './locales/pt-br/workoutDetails.json';
import ptBrWorkoutHistory from './locales/pt-br/workoutHistory.json';
import ptBrWorkoutLog from './locales/pt-br/workoutLog.json';
import ptBrWorkoutOptions from './locales/pt-br/workoutOptions.json';
import ptBrWorkouts from './locales/pt-br/workouts.json';
import ptBrWorkoutSession from './locales/pt-br/workoutSession.json';
import ptBrWorkoutSummary from './locales/pt-br/workoutSummary.json';
// ru-ru
import ruRuAccessToken from './locales/ru-ru/access_token.json';
import ruRuAddMeal from './locales/ru-ru/addMeal.json';
import ruRuAi from './locales/ru-ru/ai.json';
import ruRuBodyFat from './locales/ru-ru/body_fat.json';
import ruRuBodyMetrics from './locales/ru-ru/bodyMetrics.json';
import ruRuCamera from './locales/ru-ru/camera.json';
import ruRuCoach from './locales/ru-ru/coach.json';
import ruRuCommon from './locales/ru-ru/common.json';
import ruRuCreateWorkout from './locales/ru-ru/createWorkout.json';
import ruRuCurrentGoalsCard from './locales/ru-ru/currentGoalsCard.json';
import ruRuCycle from './locales/ru-ru/cycle.json';
import ruRuDailySummaryCard from './locales/ru-ru/dailySummaryCard.json';
import ruRuDatePicker from './locales/ru-ru/datePicker.json';
import ruRuEatingPhaseBadge from './locales/ru-ru/eatingPhaseBadge.json';
import ruRuEditFitnessDetails from './locales/ru-ru/editFitnessDetails.json';
import ruRuEditPersonalInfo from './locales/ru-ru/editPersonalInfo.json';
import ruRuEditScreenInfo from './locales/ru-ru/editScreenInfo.json';
import ruRuEditSetDetails from './locales/ru-ru/editSetDetails.json';
import ruRuEmptyStates from './locales/ru-ru/emptyStates.json';
import ruRuEndWorkout from './locales/ru-ru/endWorkout.json';
import ruRuErrors from './locales/ru-ru/errors.json';
import ruRuExercises from './locales/ru-ru/exercises.json';
import ruRuExerciseTransition from './locales/ru-ru/exerciseTransition.json';
import ruRuExpiresIn from './locales/ru-ru/expires_in.json';
import ruRuFocus from './locales/ru-ru/focus.json';
import ruRuFood from './locales/ru-ru/food.json';
import ruRuFoodFoodPortions from './locales/ru-ru/food_food_portions.json';
import ruRuFoodSearch from './locales/ru-ru/foodSearch.json';
import ruRuFreeTraining from './locales/ru-ru/freeTraining.json';
import ruRuGoalHistoryCard from './locales/ru-ru/goalHistoryCard.json';
import ruRuGoalsManagement from './locales/ru-ru/goalsManagement.json';
import ruRuHealthConnect from './locales/ru-ru/healthConnect.json';
import ruRuHome from './locales/ru-ru/home.json';
import ruRuLogSetPerformance from './locales/ru-ru/logSetPerformance.json';
import ruRuMealFoods from './locales/ru-ru/meal_foods.json';
import ruRuMeals from './locales/ru-ru/meals.json';
import ruRuNotifications from './locales/ru-ru/notifications.json';
import ruRuNutrition from './locales/ru-ru/nutrition.json';
import ruRuNutritionLogs from './locales/ru-ru/nutrition_logs.json';
import ruRuNutritionGoals from './locales/ru-ru/nutritionGoals.json';
import ruRuOnboarding from './locales/ru-ru/onboarding.json';
import ruRuOptionsSelector from './locales/ru-ru/optionsSelector.json';
import ruRuPastWorkoutHistory from './locales/ru-ru/pastWorkoutHistory.json';
import ruRuPortionSizes from './locales/ru-ru/portionSizes.json';
import ruRuProfile from './locales/ru-ru/profile.json';
import ruRuProgress from './locales/ru-ru/progress.json';
import ruRuReplaceExercise from './locales/ru-ru/replaceExercise.json';
import ruRuRestOver from './locales/ru-ru/restOver.json';
import ruRuRestTimer from './locales/ru-ru/restTimer.json';
import ruRuSessionFeedback from './locales/ru-ru/sessionFeedback.json';
import ruRuSettings from './locales/ru-ru/settings.json';
import ruRuSnackbar from './locales/ru-ru/snackbar.json';
import ruRuStartWorkout from './locales/ru-ru/startWorkout.json';
import ruRuTimePicker from './locales/ru-ru/timePicker.json';
import ruRuTokenType from './locales/ru-ru/token_type.json';
import ruRuUserMenu from './locales/ru-ru/userMenu.json';
import ruRuWorkout from './locales/ru-ru/workout.json';
import ruRuWorkoutLogSets from './locales/ru-ru/workout_log_sets.json';
import ruRuWorkoutLogs from './locales/ru-ru/workout_logs.json';
import ruRuWorkoutTemplateSets from './locales/ru-ru/workout_template_sets.json';
import ruRuWorkoutDetail from './locales/ru-ru/workoutDetail.json';
import ruRuWorkoutDetails from './locales/ru-ru/workoutDetails.json';
import ruRuWorkoutHistory from './locales/ru-ru/workoutHistory.json';
import ruRuWorkoutLog from './locales/ru-ru/workoutLog.json';
import ruRuWorkoutOptions from './locales/ru-ru/workoutOptions.json';
import ruRuWorkouts from './locales/ru-ru/workouts.json';
import ruRuWorkoutSession from './locales/ru-ru/workoutSession.json';
import ruRuWorkoutSummary from './locales/ru-ru/workoutSummary.json';
// untranslated
import untranslated from './locales/untranslated.json';

export const EN_US = 'en-US';
export const PT_BR = 'pt-BR';
export const RU_RU = 'ru-RU';

const resources = {
  [EN_US]: {
    translation: {
      ...untranslated,
      ...enUsAccessToken,
      ...enUsAddMeal,
      ...enUsAi,
      ...enUsBodyMetrics,
      ...enUsBodyFat,
      ...enUsCamera,
      ...enUsCoach,
      ...enUsCommon,
      ...enUsCreateWorkout,
      ...enUsCurrentGoalsCard,
      ...enUsCycle,
      ...enUsDailySummaryCard,
      ...enUsDatePicker,
      ...enUsEatingPhaseBadge,
      ...enUsEditFitnessDetails,
      ...enUsEditPersonalInfo,
      ...enUsEditScreenInfo,
      ...enUsEditSetDetails,
      ...enUsEmptyStates,
      ...enUsEndWorkout,
      ...enUsErrors,
      ...enUsExerciseTransition,
      ...enUsExercises,
      ...enUsExpiresIn,
      ...enUsFocus,
      ...enUsFood,
      ...enUsFoodSearch,
      ...enUsFoodFoodPortions,
      ...enUsFreeTraining,
      ...enUsGoalHistoryCard,
      ...enUsGoalsManagement,
      ...enUsHealthConnect,
      ...enUsHome,
      ...enUsLogSetPerformance,
      ...enUsMealFoods,
      ...enUsMeals,
      ...enUsNotifications,
      ...enUsNutrition,
      ...enUsNutritionGoals,
      ...enUsNutritionLogs,
      ...enUsOnboarding,
      ...enUsOptionsSelector,
      ...enUsPastWorkoutHistory,
      ...enUsPortionSizes,
      ...enUsProfile,
      ...enUsProgress,
      ...enUsReplaceExercise,
      ...enUsRestOver,
      ...enUsRestTimer,
      ...enUsSessionFeedback,
      ...enUsSettings,
      ...enUsSnackbar,
      ...enUsStartWorkout,
      ...enUsTimePicker,
      ...enUsTokenType,
      ...enUsUserMenu,
      ...enUsWorkout,
      ...enUsWorkoutDetail,
      ...enUsWorkoutDetails,
      ...enUsWorkoutHistory,
      ...enUsWorkoutLog,
      ...enUsWorkoutOptions,
      ...enUsWorkoutSession,
      ...enUsWorkoutSummary,
      ...enUsWorkoutLogSets,
      ...enUsWorkoutLogs,
      ...enUsWorkoutTemplateSets,
      ...enUsWorkouts,
    },
  },
  [PT_BR]: {
    translation: {
      ...untranslated,
      ...ptBrAccessToken,
      ...ptBrAddMeal,
      ...ptBrAi,
      ...ptBrBodyMetrics,
      ...ptBrBodyFat,
      ...ptBrCamera,
      ...ptBrCoach,
      ...ptBrCommon,
      ...ptBrCreateWorkout,
      ...ptBrCurrentGoalsCard,
      ...ptBrCycle,
      ...ptBrDailySummaryCard,
      ...ptBrDatePicker,
      ...ptBrEatingPhaseBadge,
      ...ptBrEditFitnessDetails,
      ...ptBrEditPersonalInfo,
      ...ptBrEditScreenInfo,
      ...ptBrEditSetDetails,
      ...ptBrEmptyStates,
      ...ptBrEndWorkout,
      ...ptBrErrors,
      ...ptBrExerciseTransition,
      ...ptBrExercises,
      ...ptBrExpiresIn,
      ...ptBrFocus,
      ...ptBrFood,
      ...ptBrFoodSearch,
      ...ptBrFoodFoodPortions,
      ...ptBrFreeTraining,
      ...ptBrGoalHistoryCard,
      ...ptBrGoalsManagement,
      ...ptBrHealthConnect,
      ...ptBrHome,
      ...ptBrLogSetPerformance,
      ...ptBrMealFoods,
      ...ptBrMeals,
      ...ptBrNotifications,
      ...ptBrNutrition,
      ...ptBrNutritionGoals,
      ...ptBrNutritionLogs,
      ...ptBrOnboarding,
      ...ptBrOptionsSelector,
      ...ptBrPastWorkoutHistory,
      ...ptBrPortionSizes,
      ...ptBrProfile,
      ...ptBrProgress,
      ...ptBrReplaceExercise,
      ...ptBrRestOver,
      ...ptBrRestTimer,
      ...ptBrSessionFeedback,
      ...ptBrSettings,
      ...ptBrSnackbar,
      ...ptBrStartWorkout,
      ...ptBrTimePicker,
      ...ptBrTokenType,
      ...ptBrUserMenu,
      ...ptBrWorkout,
      ...ptBrWorkoutDetail,
      ...ptBrWorkoutDetails,
      ...ptBrWorkoutHistory,
      ...ptBrWorkoutLog,
      ...ptBrWorkoutOptions,
      ...ptBrWorkoutSession,
      ...ptBrWorkoutSummary,
      ...ptBrWorkoutLogSets,
      ...ptBrWorkoutLogs,
      ...ptBrWorkoutTemplateSets,
      ...ptBrWorkouts,
    },
  },
  [RU_RU]: {
    translation: {
      ...untranslated,
      ...ruRuAccessToken,
      ...ruRuAddMeal,
      ...ruRuAi,
      ...ruRuBodyMetrics,
      ...ruRuBodyFat,
      ...ruRuCamera,
      ...ruRuCoach,
      ...ruRuCommon,
      ...ruRuCreateWorkout,
      ...ruRuCurrentGoalsCard,
      ...ruRuCycle,
      ...ruRuDailySummaryCard,
      ...ruRuDatePicker,
      ...ruRuEatingPhaseBadge,
      ...ruRuEditFitnessDetails,
      ...ruRuEditPersonalInfo,
      ...ruRuEditScreenInfo,
      ...ruRuEditSetDetails,
      ...ruRuEmptyStates,
      ...ruRuEndWorkout,
      ...ruRuErrors,
      ...ruRuExerciseTransition,
      ...ruRuExercises,
      ...ruRuExpiresIn,
      ...ruRuFocus,
      ...ruRuFood,
      ...ruRuFoodSearch,
      ...ruRuFoodFoodPortions,
      ...ruRuFreeTraining,
      ...ruRuGoalHistoryCard,
      ...ruRuGoalsManagement,
      ...ruRuHealthConnect,
      ...ruRuHome,
      ...ruRuLogSetPerformance,
      ...ruRuMealFoods,
      ...ruRuMeals,
      ...ruRuNotifications,
      ...ruRuNutrition,
      ...ruRuNutritionGoals,
      ...ruRuNutritionLogs,
      ...ruRuOnboarding,
      ...ruRuOptionsSelector,
      ...ruRuPastWorkoutHistory,
      ...ruRuPortionSizes,
      ...ruRuProfile,
      ...ruRuProgress,
      ...ruRuReplaceExercise,
      ...ruRuRestOver,
      ...ruRuRestTimer,
      ...ruRuSessionFeedback,
      ...ruRuSettings,
      ...ruRuSnackbar,
      ...ruRuStartWorkout,
      ...ruRuTimePicker,
      ...ruRuTokenType,
      ...ruRuUserMenu,
      ...ruRuWorkout,
      ...ruRuWorkoutDetail,
      ...ruRuWorkoutDetails,
      ...ruRuWorkoutHistory,
      ...ruRuWorkoutLog,
      ...ruRuWorkoutOptions,
      ...ruRuWorkoutSession,
      ...ruRuWorkoutSummary,
      ...ruRuWorkoutLogSets,
      ...ruRuWorkoutLogs,
      ...ruRuWorkoutTemplateSets,
      ...ruRuWorkouts,
    },
  },
};

export type LanguageKeys = keyof typeof resources;

export const LOCALE_MAP = {
  [EN_US]: localeEnUS,
  [PT_BR]: localePtBR,
  [RU_RU]: localeRu,
};

export const AVAILABLE_LANGUAGES = Object.keys(resources) as LanguageKeys[];

const systemLocales = Localization.getLocales();

i18n.use(initReactI18next).init({
  // compatibilityJSON: 'v3',
  debug: __DEV__,
  fallbackLng: EN_US,
  interpolation: {
    escapeValue: false,
  },
  lng:
    systemLocales.find((locale) => AVAILABLE_LANGUAGES.includes(locale.languageTag as LanguageKeys))
      ?.languageTag || EN_US,
  resources,
});

export const languageLabels: Record<string, string> = {
  [EN_US]: i18n.t('untranslated.en-us'),
  [PT_BR]: i18n.t('untranslated.pt-br'),
  [RU_RU]: i18n.t('untranslated.ru-ru'),
};

export default i18n;
