// ATTENTION: This file and locales/untranslated.json are generated by scripts/generateLangFile.js
// Do not edit this file manually. Changes will be overwritten.

import 'intl-pluralrules';

import {
  enUS as localeEnUS,
  es as localeEs,
  nl as localeNl,
  ptBR as localePtBR,
  ru as localeRu,
} from 'date-fns/locale';
import * as Localization from 'expo-localization';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Exercise data
import exercisesEnUs from '@/data/exercisesEnUS.json';
import exercisesEsEs from '@/data/exercisesEsEs.json';
import exercisesNlNl from '@/data/exercisesNlNl.json';
import exercisesPtBr from '@/data/exercisesPtBr.json';
import exercisesRuRu from '@/data/exercisesRuRu.json';

// en-us
import enUsAccessToken from './locales/en-us/access_token.json';
import enUsAddMeal from './locales/en-us/addMeal.json';
import enUsAi from './locales/en-us/ai.json';
import enUsBodyFat from './locales/en-us/body_fat.json';
import enUsBodyMetrics from './locales/en-us/bodyMetrics.json';
import enUsCamera from './locales/en-us/camera.json';
import enUsCoach from './locales/en-us/coach.json';
import enUsCommon from './locales/en-us/common.json';
import enUsCreateWorkout from './locales/en-us/createWorkout.json';
import enUsCurrentGoalsCard from './locales/en-us/currentGoalsCard.json';
import enUsCycle from './locales/en-us/cycle.json';
import enUsDailySummaryCard from './locales/en-us/dailySummaryCard.json';
import enUsDatePicker from './locales/en-us/datePicker.json';
import enUsEatingPhaseBadge from './locales/en-us/eatingPhaseBadge.json';
import enUsEditFitnessDetails from './locales/en-us/editFitnessDetails.json';
import enUsEditPersonalInfo from './locales/en-us/editPersonalInfo.json';
import enUsEditScreenInfo from './locales/en-us/editScreenInfo.json';
import enUsEditSetDetails from './locales/en-us/editSetDetails.json';
import enUsEmptyStates from './locales/en-us/emptyStates.json';
import enUsEndWorkout from './locales/en-us/endWorkout.json';
import enUsErrors from './locales/en-us/errors.json';
import enUsExerciseGoals from './locales/en-us/exerciseGoals.json';
import enUsExercises from './locales/en-us/exercises.json';
import enUsExerciseTransition from './locales/en-us/exerciseTransition.json';
import enUsExpiresIn from './locales/en-us/expires_in.json';
import enUsFocus from './locales/en-us/focus.json';
import enUsFood from './locales/en-us/food.json';
import enUsFoodFoodPortions from './locales/en-us/food_food_portions.json';
import enUsFoodSearch from './locales/en-us/foodSearch.json';
import enUsFreeTraining from './locales/en-us/freeTraining.json';
import enUsGoalHistoryCard from './locales/en-us/goalHistoryCard.json';
import enUsGoalsManagement from './locales/en-us/goalsManagement.json';
import enUsHealthConnect from './locales/en-us/healthConnect.json';
import enUsHeightPicker from './locales/en-us/heightPicker.json';
import enUsHome from './locales/en-us/home.json';
import enUsLogSetPerformance from './locales/en-us/logSetPerformance.json';
import enUsMealFoods from './locales/en-us/meal_foods.json';
import enUsMeals from './locales/en-us/meals.json';
import enUsNotifications from './locales/en-us/notifications.json';
import enUsNutrition from './locales/en-us/nutrition.json';
import enUsNutritionLogs from './locales/en-us/nutrition_logs.json';
import enUsNutritionGoals from './locales/en-us/nutritionGoals.json';
import enUsOnboarding from './locales/en-us/onboarding.json';
import enUsOptionsSelector from './locales/en-us/optionsSelector.json';
import enUsPastWorkoutHistory from './locales/en-us/pastWorkoutHistory.json';
import enUsPortionSizes from './locales/en-us/portionSizes.json';
import enUsProfile from './locales/en-us/profile.json';
import enUsProgress from './locales/en-us/progress.json';
import enUsReplaceExercise from './locales/en-us/replaceExercise.json';
import enUsRestOver from './locales/en-us/restOver.json';
import enUsRestTimer from './locales/en-us/restTimer.json';
import enUsSessionFeedback from './locales/en-us/sessionFeedback.json';
import enUsSettings from './locales/en-us/settings.json';
import enUsSnackbar from './locales/en-us/snackbar.json';
import enUsStartWorkout from './locales/en-us/startWorkout.json';
import enUsTimePicker from './locales/en-us/timePicker.json';
import enUsTokenType from './locales/en-us/token_type.json';
import enUsUserMenu from './locales/en-us/userMenu.json';
import enUsWorkout from './locales/en-us/workout.json';
import enUsWorkoutLogSets from './locales/en-us/workout_log_sets.json';
import enUsWorkoutLogs from './locales/en-us/workout_logs.json';
import enUsWorkoutTemplateSets from './locales/en-us/workout_template_sets.json';
import enUsWorkoutDetail from './locales/en-us/workoutDetail.json';
import enUsWorkoutDetails from './locales/en-us/workoutDetails.json';
import enUsWorkoutHistory from './locales/en-us/workoutHistory.json';
import enUsWorkoutLog from './locales/en-us/workoutLog.json';
import enUsWorkoutOptions from './locales/en-us/workoutOptions.json';
import enUsWorkouts from './locales/en-us/workouts.json';
import enUsWorkoutSession from './locales/en-us/workoutSession.json';
import enUsWorkoutSummary from './locales/en-us/workoutSummary.json';
// es-es
import esEsAccessToken from './locales/es-es/access_token.json';
import esEsAddMeal from './locales/es-es/addMeal.json';
import esEsAi from './locales/es-es/ai.json';
import esEsBodyFat from './locales/es-es/body_fat.json';
import esEsBodyMetrics from './locales/es-es/bodyMetrics.json';
import esEsCamera from './locales/es-es/camera.json';
import esEsCoach from './locales/es-es/coach.json';
import esEsCommon from './locales/es-es/common.json';
import esEsCreateWorkout from './locales/es-es/createWorkout.json';
import esEsCurrentGoalsCard from './locales/es-es/currentGoalsCard.json';
import esEsCycle from './locales/es-es/cycle.json';
import esEsDailySummaryCard from './locales/es-es/dailySummaryCard.json';
import esEsDatePicker from './locales/es-es/datePicker.json';
import esEsEatingPhaseBadge from './locales/es-es/eatingPhaseBadge.json';
import esEsEditFitnessDetails from './locales/es-es/editFitnessDetails.json';
import esEsEditPersonalInfo from './locales/es-es/editPersonalInfo.json';
import esEsEditScreenInfo from './locales/es-es/editScreenInfo.json';
import esEsEditSetDetails from './locales/es-es/editSetDetails.json';
import esEsEmptyStates from './locales/es-es/emptyStates.json';
import esEsEndWorkout from './locales/es-es/endWorkout.json';
import esEsErrors from './locales/es-es/errors.json';
import esEsExerciseGoals from './locales/es-es/exerciseGoals.json';
import esEsExercises from './locales/es-es/exercises.json';
import esEsExerciseTransition from './locales/es-es/exerciseTransition.json';
import esEsExpiresIn from './locales/es-es/expires_in.json';
import esEsFocus from './locales/es-es/focus.json';
import esEsFood from './locales/es-es/food.json';
import esEsFoodFoodPortions from './locales/es-es/food_food_portions.json';
import esEsFoodSearch from './locales/es-es/foodSearch.json';
import esEsFreeTraining from './locales/es-es/freeTraining.json';
import esEsGoalHistoryCard from './locales/es-es/goalHistoryCard.json';
import esEsGoalsManagement from './locales/es-es/goalsManagement.json';
import esEsHealthConnect from './locales/es-es/healthConnect.json';
import esEsHeightPicker from './locales/es-es/heightPicker.json';
import esEsHome from './locales/es-es/home.json';
import esEsLogSetPerformance from './locales/es-es/logSetPerformance.json';
import esEsMealFoods from './locales/es-es/meal_foods.json';
import esEsMeals from './locales/es-es/meals.json';
import esEsNotifications from './locales/es-es/notifications.json';
import esEsNutrition from './locales/es-es/nutrition.json';
import esEsNutritionLogs from './locales/es-es/nutrition_logs.json';
import esEsNutritionGoals from './locales/es-es/nutritionGoals.json';
import esEsOnboarding from './locales/es-es/onboarding.json';
import esEsOptionsSelector from './locales/es-es/optionsSelector.json';
import esEsPastWorkoutHistory from './locales/es-es/pastWorkoutHistory.json';
import esEsPortionSizes from './locales/es-es/portionSizes.json';
import esEsProfile from './locales/es-es/profile.json';
import esEsProgress from './locales/es-es/progress.json';
import esEsReplaceExercise from './locales/es-es/replaceExercise.json';
import esEsRestOver from './locales/es-es/restOver.json';
import esEsRestTimer from './locales/es-es/restTimer.json';
import esEsSessionFeedback from './locales/es-es/sessionFeedback.json';
import esEsSettings from './locales/es-es/settings.json';
import esEsSnackbar from './locales/es-es/snackbar.json';
import esEsStartWorkout from './locales/es-es/startWorkout.json';
import esEsTimePicker from './locales/es-es/timePicker.json';
import esEsTokenType from './locales/es-es/token_type.json';
import esEsUserMenu from './locales/es-es/userMenu.json';
import esEsWorkout from './locales/es-es/workout.json';
import esEsWorkoutLogSets from './locales/es-es/workout_log_sets.json';
import esEsWorkoutLogs from './locales/es-es/workout_logs.json';
import esEsWorkoutTemplateSets from './locales/es-es/workout_template_sets.json';
import esEsWorkoutDetail from './locales/es-es/workoutDetail.json';
import esEsWorkoutDetails from './locales/es-es/workoutDetails.json';
import esEsWorkoutHistory from './locales/es-es/workoutHistory.json';
import esEsWorkoutLog from './locales/es-es/workoutLog.json';
import esEsWorkoutOptions from './locales/es-es/workoutOptions.json';
import esEsWorkouts from './locales/es-es/workouts.json';
import esEsWorkoutSession from './locales/es-es/workoutSession.json';
import esEsWorkoutSummary from './locales/es-es/workoutSummary.json';
// nl-nl
import nlNlAccessToken from './locales/nl-nl/access_token.json';
import nlNlAddMeal from './locales/nl-nl/addMeal.json';
import nlNlAi from './locales/nl-nl/ai.json';
import nlNlBodyFat from './locales/nl-nl/body_fat.json';
import nlNlBodyMetrics from './locales/nl-nl/bodyMetrics.json';
import nlNlCamera from './locales/nl-nl/camera.json';
import nlNlCoach from './locales/nl-nl/coach.json';
import nlNlCommon from './locales/nl-nl/common.json';
import nlNlCreateWorkout from './locales/nl-nl/createWorkout.json';
import nlNlCurrentGoalsCard from './locales/nl-nl/currentGoalsCard.json';
import nlNlCycle from './locales/nl-nl/cycle.json';
import nlNlDailySummaryCard from './locales/nl-nl/dailySummaryCard.json';
import nlNlDatePicker from './locales/nl-nl/datePicker.json';
import nlNlEatingPhaseBadge from './locales/nl-nl/eatingPhaseBadge.json';
import nlNlEditFitnessDetails from './locales/nl-nl/editFitnessDetails.json';
import nlNlEditPersonalInfo from './locales/nl-nl/editPersonalInfo.json';
import nlNlEditScreenInfo from './locales/nl-nl/editScreenInfo.json';
import nlNlEditSetDetails from './locales/nl-nl/editSetDetails.json';
import nlNlEmptyStates from './locales/nl-nl/emptyStates.json';
import nlNlEndWorkout from './locales/nl-nl/endWorkout.json';
import nlNlErrors from './locales/nl-nl/errors.json';
import nlNlExerciseGoals from './locales/nl-nl/exerciseGoals.json';
import nlNlExercises from './locales/nl-nl/exercises.json';
import nlNlExerciseTransition from './locales/nl-nl/exerciseTransition.json';
import nlNlExpiresIn from './locales/nl-nl/expires_in.json';
import nlNlFocus from './locales/nl-nl/focus.json';
import nlNlFood from './locales/nl-nl/food.json';
import nlNlFoodFoodPortions from './locales/nl-nl/food_food_portions.json';
import nlNlFoodSearch from './locales/nl-nl/foodSearch.json';
import nlNlFreeTraining from './locales/nl-nl/freeTraining.json';
import nlNlGoalHistoryCard from './locales/nl-nl/goalHistoryCard.json';
import nlNlGoalsManagement from './locales/nl-nl/goalsManagement.json';
import nlNlHealthConnect from './locales/nl-nl/healthConnect.json';
import nlNlHeightPicker from './locales/nl-nl/heightPicker.json';
import nlNlHome from './locales/nl-nl/home.json';
import nlNlLogSetPerformance from './locales/nl-nl/logSetPerformance.json';
import nlNlMealFoods from './locales/nl-nl/meal_foods.json';
import nlNlMeals from './locales/nl-nl/meals.json';
import nlNlNotifications from './locales/nl-nl/notifications.json';
import nlNlNutrition from './locales/nl-nl/nutrition.json';
import nlNlNutritionLogs from './locales/nl-nl/nutrition_logs.json';
import nlNlNutritionGoals from './locales/nl-nl/nutritionGoals.json';
import nlNlOnboarding from './locales/nl-nl/onboarding.json';
import nlNlOptionsSelector from './locales/nl-nl/optionsSelector.json';
import nlNlPastWorkoutHistory from './locales/nl-nl/pastWorkoutHistory.json';
import nlNlPortionSizes from './locales/nl-nl/portionSizes.json';
import nlNlProfile from './locales/nl-nl/profile.json';
import nlNlProgress from './locales/nl-nl/progress.json';
import nlNlReplaceExercise from './locales/nl-nl/replaceExercise.json';
import nlNlRestOver from './locales/nl-nl/restOver.json';
import nlNlRestTimer from './locales/nl-nl/restTimer.json';
import nlNlSessionFeedback from './locales/nl-nl/sessionFeedback.json';
import nlNlSettings from './locales/nl-nl/settings.json';
import nlNlSnackbar from './locales/nl-nl/snackbar.json';
import nlNlStartWorkout from './locales/nl-nl/startWorkout.json';
import nlNlTimePicker from './locales/nl-nl/timePicker.json';
import nlNlTokenType from './locales/nl-nl/token_type.json';
import nlNlUserMenu from './locales/nl-nl/userMenu.json';
import nlNlWorkout from './locales/nl-nl/workout.json';
import nlNlWorkoutLogSets from './locales/nl-nl/workout_log_sets.json';
import nlNlWorkoutLogs from './locales/nl-nl/workout_logs.json';
import nlNlWorkoutTemplateSets from './locales/nl-nl/workout_template_sets.json';
import nlNlWorkoutDetail from './locales/nl-nl/workoutDetail.json';
import nlNlWorkoutDetails from './locales/nl-nl/workoutDetails.json';
import nlNlWorkoutHistory from './locales/nl-nl/workoutHistory.json';
import nlNlWorkoutLog from './locales/nl-nl/workoutLog.json';
import nlNlWorkoutOptions from './locales/nl-nl/workoutOptions.json';
import nlNlWorkouts from './locales/nl-nl/workouts.json';
import nlNlWorkoutSession from './locales/nl-nl/workoutSession.json';
import nlNlWorkoutSummary from './locales/nl-nl/workoutSummary.json';
// pt-br
import ptBrAccessToken from './locales/pt-br/access_token.json';
import ptBrAddMeal from './locales/pt-br/addMeal.json';
import ptBrAi from './locales/pt-br/ai.json';
import ptBrBodyFat from './locales/pt-br/body_fat.json';
import ptBrBodyMetrics from './locales/pt-br/bodyMetrics.json';
import ptBrCamera from './locales/pt-br/camera.json';
import ptBrCoach from './locales/pt-br/coach.json';
import ptBrCommon from './locales/pt-br/common.json';
import ptBrCreateWorkout from './locales/pt-br/createWorkout.json';
import ptBrCurrentGoalsCard from './locales/pt-br/currentGoalsCard.json';
import ptBrCycle from './locales/pt-br/cycle.json';
import ptBrDailySummaryCard from './locales/pt-br/dailySummaryCard.json';
import ptBrDatePicker from './locales/pt-br/datePicker.json';
import ptBrEatingPhaseBadge from './locales/pt-br/eatingPhaseBadge.json';
import ptBrEditFitnessDetails from './locales/pt-br/editFitnessDetails.json';
import ptBrEditPersonalInfo from './locales/pt-br/editPersonalInfo.json';
import ptBrEditScreenInfo from './locales/pt-br/editScreenInfo.json';
import ptBrEditSetDetails from './locales/pt-br/editSetDetails.json';
import ptBrEmptyStates from './locales/pt-br/emptyStates.json';
import ptBrEndWorkout from './locales/pt-br/endWorkout.json';
import ptBrErrors from './locales/pt-br/errors.json';
import ptBrExerciseGoals from './locales/pt-br/exerciseGoals.json';
import ptBrExercises from './locales/pt-br/exercises.json';
import ptBrExerciseTransition from './locales/pt-br/exerciseTransition.json';
import ptBrExpiresIn from './locales/pt-br/expires_in.json';
import ptBrFocus from './locales/pt-br/focus.json';
import ptBrFood from './locales/pt-br/food.json';
import ptBrFoodFoodPortions from './locales/pt-br/food_food_portions.json';
import ptBrFoodSearch from './locales/pt-br/foodSearch.json';
import ptBrFreeTraining from './locales/pt-br/freeTraining.json';
import ptBrGoalHistoryCard from './locales/pt-br/goalHistoryCard.json';
import ptBrGoalsManagement from './locales/pt-br/goalsManagement.json';
import ptBrHealthConnect from './locales/pt-br/healthConnect.json';
import ptBrHeightPicker from './locales/pt-br/heightPicker.json';
import ptBrHome from './locales/pt-br/home.json';
import ptBrLogSetPerformance from './locales/pt-br/logSetPerformance.json';
import ptBrMealFoods from './locales/pt-br/meal_foods.json';
import ptBrMeals from './locales/pt-br/meals.json';
import ptBrNotifications from './locales/pt-br/notifications.json';
import ptBrNutrition from './locales/pt-br/nutrition.json';
import ptBrNutritionLogs from './locales/pt-br/nutrition_logs.json';
import ptBrNutritionGoals from './locales/pt-br/nutritionGoals.json';
import ptBrOnboarding from './locales/pt-br/onboarding.json';
import ptBrOptionsSelector from './locales/pt-br/optionsSelector.json';
import ptBrPastWorkoutHistory from './locales/pt-br/pastWorkoutHistory.json';
import ptBrPortionSizes from './locales/pt-br/portionSizes.json';
import ptBrProfile from './locales/pt-br/profile.json';
import ptBrProgress from './locales/pt-br/progress.json';
import ptBrReplaceExercise from './locales/pt-br/replaceExercise.json';
import ptBrRestOver from './locales/pt-br/restOver.json';
import ptBrRestTimer from './locales/pt-br/restTimer.json';
import ptBrSessionFeedback from './locales/pt-br/sessionFeedback.json';
import ptBrSettings from './locales/pt-br/settings.json';
import ptBrSnackbar from './locales/pt-br/snackbar.json';
import ptBrStartWorkout from './locales/pt-br/startWorkout.json';
import ptBrTimePicker from './locales/pt-br/timePicker.json';
import ptBrTokenType from './locales/pt-br/token_type.json';
import ptBrUserMenu from './locales/pt-br/userMenu.json';
import ptBrWorkout from './locales/pt-br/workout.json';
import ptBrWorkoutLogSets from './locales/pt-br/workout_log_sets.json';
import ptBrWorkoutLogs from './locales/pt-br/workout_logs.json';
import ptBrWorkoutTemplateSets from './locales/pt-br/workout_template_sets.json';
import ptBrWorkoutDetail from './locales/pt-br/workoutDetail.json';
import ptBrWorkoutDetails from './locales/pt-br/workoutDetails.json';
import ptBrWorkoutHistory from './locales/pt-br/workoutHistory.json';
import ptBrWorkoutLog from './locales/pt-br/workoutLog.json';
import ptBrWorkoutOptions from './locales/pt-br/workoutOptions.json';
import ptBrWorkouts from './locales/pt-br/workouts.json';
import ptBrWorkoutSession from './locales/pt-br/workoutSession.json';
import ptBrWorkoutSummary from './locales/pt-br/workoutSummary.json';
// ru-ru
import ruRuAccessToken from './locales/ru-ru/access_token.json';
import ruRuAddMeal from './locales/ru-ru/addMeal.json';
import ruRuAi from './locales/ru-ru/ai.json';
import ruRuBodyFat from './locales/ru-ru/body_fat.json';
import ruRuBodyMetrics from './locales/ru-ru/bodyMetrics.json';
import ruRuCamera from './locales/ru-ru/camera.json';
import ruRuCoach from './locales/ru-ru/coach.json';
import ruRuCommon from './locales/ru-ru/common.json';
import ruRuCreateWorkout from './locales/ru-ru/createWorkout.json';
import ruRuCurrentGoalsCard from './locales/ru-ru/currentGoalsCard.json';
import ruRuCycle from './locales/ru-ru/cycle.json';
import ruRuDailySummaryCard from './locales/ru-ru/dailySummaryCard.json';
import ruRuDatePicker from './locales/ru-ru/datePicker.json';
import ruRuEatingPhaseBadge from './locales/ru-ru/eatingPhaseBadge.json';
import ruRuEditFitnessDetails from './locales/ru-ru/editFitnessDetails.json';
import ruRuEditPersonalInfo from './locales/ru-ru/editPersonalInfo.json';
import ruRuEditScreenInfo from './locales/ru-ru/editScreenInfo.json';
import ruRuEditSetDetails from './locales/ru-ru/editSetDetails.json';
import ruRuEmptyStates from './locales/ru-ru/emptyStates.json';
import ruRuEndWorkout from './locales/ru-ru/endWorkout.json';
import ruRuErrors from './locales/ru-ru/errors.json';
import ruRuExerciseGoals from './locales/ru-ru/exerciseGoals.json';
import ruRuExercises from './locales/ru-ru/exercises.json';
import ruRuExerciseTransition from './locales/ru-ru/exerciseTransition.json';
import ruRuExpiresIn from './locales/ru-ru/expires_in.json';
import ruRuFocus from './locales/ru-ru/focus.json';
import ruRuFood from './locales/ru-ru/food.json';
import ruRuFoodFoodPortions from './locales/ru-ru/food_food_portions.json';
import ruRuFoodSearch from './locales/ru-ru/foodSearch.json';
import ruRuFreeTraining from './locales/ru-ru/freeTraining.json';
import ruRuGoalHistoryCard from './locales/ru-ru/goalHistoryCard.json';
import ruRuGoalsManagement from './locales/ru-ru/goalsManagement.json';
import ruRuHealthConnect from './locales/ru-ru/healthConnect.json';
import ruRuHeightPicker from './locales/ru-ru/heightPicker.json';
import ruRuHome from './locales/ru-ru/home.json';
import ruRuLogSetPerformance from './locales/ru-ru/logSetPerformance.json';
import ruRuMealFoods from './locales/ru-ru/meal_foods.json';
import ruRuMeals from './locales/ru-ru/meals.json';
import ruRuNotifications from './locales/ru-ru/notifications.json';
import ruRuNutrition from './locales/ru-ru/nutrition.json';
import ruRuNutritionLogs from './locales/ru-ru/nutrition_logs.json';
import ruRuNutritionGoals from './locales/ru-ru/nutritionGoals.json';
import ruRuOnboarding from './locales/ru-ru/onboarding.json';
import ruRuOptionsSelector from './locales/ru-ru/optionsSelector.json';
import ruRuPastWorkoutHistory from './locales/ru-ru/pastWorkoutHistory.json';
import ruRuPortionSizes from './locales/ru-ru/portionSizes.json';
import ruRuProfile from './locales/ru-ru/profile.json';
import ruRuProgress from './locales/ru-ru/progress.json';
import ruRuReplaceExercise from './locales/ru-ru/replaceExercise.json';
import ruRuRestOver from './locales/ru-ru/restOver.json';
import ruRuRestTimer from './locales/ru-ru/restTimer.json';
import ruRuSessionFeedback from './locales/ru-ru/sessionFeedback.json';
import ruRuSettings from './locales/ru-ru/settings.json';
import ruRuSnackbar from './locales/ru-ru/snackbar.json';
import ruRuStartWorkout from './locales/ru-ru/startWorkout.json';
import ruRuTimePicker from './locales/ru-ru/timePicker.json';
import ruRuTokenType from './locales/ru-ru/token_type.json';
import ruRuUserMenu from './locales/ru-ru/userMenu.json';
import ruRuWorkout from './locales/ru-ru/workout.json';
import ruRuWorkoutLogSets from './locales/ru-ru/workout_log_sets.json';
import ruRuWorkoutLogs from './locales/ru-ru/workout_logs.json';
import ruRuWorkoutTemplateSets from './locales/ru-ru/workout_template_sets.json';
import ruRuWorkoutDetail from './locales/ru-ru/workoutDetail.json';
import ruRuWorkoutDetails from './locales/ru-ru/workoutDetails.json';
import ruRuWorkoutHistory from './locales/ru-ru/workoutHistory.json';
import ruRuWorkoutLog from './locales/ru-ru/workoutLog.json';
import ruRuWorkoutOptions from './locales/ru-ru/workoutOptions.json';
import ruRuWorkouts from './locales/ru-ru/workouts.json';
import ruRuWorkoutSession from './locales/ru-ru/workoutSession.json';
import ruRuWorkoutSummary from './locales/ru-ru/workoutSummary.json';
// untranslated
import untranslated from './locales/untranslated.json';

export const EN_US = 'en-US';
export const ES_ES = 'es-ES';
export const NL_NL = 'nl-NL';
export const PT_BR = 'pt-BR';
export const RU_RU = 'ru-RU';

// Exercise exports
export const EXERCISES_JSON = {
  [EN_US]: exercisesEnUs,
  [ES_ES]: exercisesEsEs,
  [NL_NL]: exercisesNlNl,
  [PT_BR]: exercisesPtBr,
  [RU_RU]: exercisesRuRu,
};

const resources = {
  [EN_US]: {
    translation: {
      ...untranslated,
      ...enUsAccessToken,
      ...enUsAddMeal,
      ...enUsAi,
      ...enUsBodyMetrics,
      ...enUsBodyFat,
      ...enUsCamera,
      ...enUsCoach,
      ...enUsCommon,
      ...enUsCreateWorkout,
      ...enUsCurrentGoalsCard,
      ...enUsCycle,
      ...enUsDailySummaryCard,
      ...enUsDatePicker,
      ...enUsEatingPhaseBadge,
      ...enUsEditFitnessDetails,
      ...enUsEditPersonalInfo,
      ...enUsEditScreenInfo,
      ...enUsEditSetDetails,
      ...enUsEmptyStates,
      ...enUsEndWorkout,
      ...enUsErrors,
      ...enUsExerciseGoals,
      ...enUsExerciseTransition,
      ...enUsExercises,
      ...enUsExpiresIn,
      ...enUsFocus,
      ...enUsFood,
      ...enUsFoodSearch,
      ...enUsFoodFoodPortions,
      ...enUsFreeTraining,
      ...enUsGoalHistoryCard,
      ...enUsGoalsManagement,
      ...enUsHealthConnect,
      ...enUsHeightPicker,
      ...enUsHome,
      ...enUsLogSetPerformance,
      ...enUsMealFoods,
      ...enUsMeals,
      ...enUsNotifications,
      ...enUsNutrition,
      ...enUsNutritionGoals,
      ...enUsNutritionLogs,
      ...enUsOnboarding,
      ...enUsOptionsSelector,
      ...enUsPastWorkoutHistory,
      ...enUsPortionSizes,
      ...enUsProfile,
      ...enUsProgress,
      ...enUsReplaceExercise,
      ...enUsRestOver,
      ...enUsRestTimer,
      ...enUsSessionFeedback,
      ...enUsSettings,
      ...enUsSnackbar,
      ...enUsStartWorkout,
      ...enUsTimePicker,
      ...enUsTokenType,
      ...enUsUserMenu,
      ...enUsWorkout,
      ...enUsWorkoutDetail,
      ...enUsWorkoutDetails,
      ...enUsWorkoutHistory,
      ...enUsWorkoutLog,
      ...enUsWorkoutOptions,
      ...enUsWorkoutSession,
      ...enUsWorkoutSummary,
      ...enUsWorkoutLogSets,
      ...enUsWorkoutLogs,
      ...enUsWorkoutTemplateSets,
      ...enUsWorkouts,
    },
  },
  [ES_ES]: {
    translation: {
      ...untranslated,
      ...esEsAccessToken,
      ...esEsAddMeal,
      ...esEsAi,
      ...esEsBodyMetrics,
      ...esEsBodyFat,
      ...esEsCamera,
      ...esEsCoach,
      ...esEsCommon,
      ...esEsCreateWorkout,
      ...esEsCurrentGoalsCard,
      ...esEsCycle,
      ...esEsDailySummaryCard,
      ...esEsDatePicker,
      ...esEsEatingPhaseBadge,
      ...esEsEditFitnessDetails,
      ...esEsEditPersonalInfo,
      ...esEsEditScreenInfo,
      ...esEsEditSetDetails,
      ...esEsEmptyStates,
      ...esEsEndWorkout,
      ...esEsErrors,
      ...esEsExerciseGoals,
      ...esEsExerciseTransition,
      ...esEsExercises,
      ...esEsExpiresIn,
      ...esEsFocus,
      ...esEsFood,
      ...esEsFoodSearch,
      ...esEsFoodFoodPortions,
      ...esEsFreeTraining,
      ...esEsGoalHistoryCard,
      ...esEsGoalsManagement,
      ...esEsHealthConnect,
      ...esEsHeightPicker,
      ...esEsHome,
      ...esEsLogSetPerformance,
      ...esEsMealFoods,
      ...esEsMeals,
      ...esEsNotifications,
      ...esEsNutrition,
      ...esEsNutritionGoals,
      ...esEsNutritionLogs,
      ...esEsOnboarding,
      ...esEsOptionsSelector,
      ...esEsPastWorkoutHistory,
      ...esEsPortionSizes,
      ...esEsProfile,
      ...esEsProgress,
      ...esEsReplaceExercise,
      ...esEsRestOver,
      ...esEsRestTimer,
      ...esEsSessionFeedback,
      ...esEsSettings,
      ...esEsSnackbar,
      ...esEsStartWorkout,
      ...esEsTimePicker,
      ...esEsTokenType,
      ...esEsUserMenu,
      ...esEsWorkout,
      ...esEsWorkoutDetail,
      ...esEsWorkoutDetails,
      ...esEsWorkoutHistory,
      ...esEsWorkoutLog,
      ...esEsWorkoutOptions,
      ...esEsWorkoutSession,
      ...esEsWorkoutSummary,
      ...esEsWorkoutLogSets,
      ...esEsWorkoutLogs,
      ...esEsWorkoutTemplateSets,
      ...esEsWorkouts,
    },
  },
  [NL_NL]: {
    translation: {
      ...untranslated,
      ...nlNlAccessToken,
      ...nlNlAddMeal,
      ...nlNlAi,
      ...nlNlBodyMetrics,
      ...nlNlBodyFat,
      ...nlNlCamera,
      ...nlNlCoach,
      ...nlNlCommon,
      ...nlNlCreateWorkout,
      ...nlNlCurrentGoalsCard,
      ...nlNlCycle,
      ...nlNlDailySummaryCard,
      ...nlNlDatePicker,
      ...nlNlEatingPhaseBadge,
      ...nlNlEditFitnessDetails,
      ...nlNlEditPersonalInfo,
      ...nlNlEditScreenInfo,
      ...nlNlEditSetDetails,
      ...nlNlEmptyStates,
      ...nlNlEndWorkout,
      ...nlNlErrors,
      ...nlNlExerciseGoals,
      ...nlNlExerciseTransition,
      ...nlNlExercises,
      ...nlNlExpiresIn,
      ...nlNlFocus,
      ...nlNlFood,
      ...nlNlFoodSearch,
      ...nlNlFoodFoodPortions,
      ...nlNlFreeTraining,
      ...nlNlGoalHistoryCard,
      ...nlNlGoalsManagement,
      ...nlNlHealthConnect,
      ...nlNlHeightPicker,
      ...nlNlHome,
      ...nlNlLogSetPerformance,
      ...nlNlMealFoods,
      ...nlNlMeals,
      ...nlNlNotifications,
      ...nlNlNutrition,
      ...nlNlNutritionGoals,
      ...nlNlNutritionLogs,
      ...nlNlOnboarding,
      ...nlNlOptionsSelector,
      ...nlNlPastWorkoutHistory,
      ...nlNlPortionSizes,
      ...nlNlProfile,
      ...nlNlProgress,
      ...nlNlReplaceExercise,
      ...nlNlRestOver,
      ...nlNlRestTimer,
      ...nlNlSessionFeedback,
      ...nlNlSettings,
      ...nlNlSnackbar,
      ...nlNlStartWorkout,
      ...nlNlTimePicker,
      ...nlNlTokenType,
      ...nlNlUserMenu,
      ...nlNlWorkout,
      ...nlNlWorkoutDetail,
      ...nlNlWorkoutDetails,
      ...nlNlWorkoutHistory,
      ...nlNlWorkoutLog,
      ...nlNlWorkoutOptions,
      ...nlNlWorkoutSession,
      ...nlNlWorkoutSummary,
      ...nlNlWorkoutLogSets,
      ...nlNlWorkoutLogs,
      ...nlNlWorkoutTemplateSets,
      ...nlNlWorkouts,
    },
  },
  [PT_BR]: {
    translation: {
      ...untranslated,
      ...ptBrAccessToken,
      ...ptBrAddMeal,
      ...ptBrAi,
      ...ptBrBodyMetrics,
      ...ptBrBodyFat,
      ...ptBrCamera,
      ...ptBrCoach,
      ...ptBrCommon,
      ...ptBrCreateWorkout,
      ...ptBrCurrentGoalsCard,
      ...ptBrCycle,
      ...ptBrDailySummaryCard,
      ...ptBrDatePicker,
      ...ptBrEatingPhaseBadge,
      ...ptBrEditFitnessDetails,
      ...ptBrEditPersonalInfo,
      ...ptBrEditScreenInfo,
      ...ptBrEditSetDetails,
      ...ptBrEmptyStates,
      ...ptBrEndWorkout,
      ...ptBrErrors,
      ...ptBrExerciseGoals,
      ...ptBrExerciseTransition,
      ...ptBrExercises,
      ...ptBrExpiresIn,
      ...ptBrFocus,
      ...ptBrFood,
      ...ptBrFoodSearch,
      ...ptBrFoodFoodPortions,
      ...ptBrFreeTraining,
      ...ptBrGoalHistoryCard,
      ...ptBrGoalsManagement,
      ...ptBrHealthConnect,
      ...ptBrHeightPicker,
      ...ptBrHome,
      ...ptBrLogSetPerformance,
      ...ptBrMealFoods,
      ...ptBrMeals,
      ...ptBrNotifications,
      ...ptBrNutrition,
      ...ptBrNutritionGoals,
      ...ptBrNutritionLogs,
      ...ptBrOnboarding,
      ...ptBrOptionsSelector,
      ...ptBrPastWorkoutHistory,
      ...ptBrPortionSizes,
      ...ptBrProfile,
      ...ptBrProgress,
      ...ptBrReplaceExercise,
      ...ptBrRestOver,
      ...ptBrRestTimer,
      ...ptBrSessionFeedback,
      ...ptBrSettings,
      ...ptBrSnackbar,
      ...ptBrStartWorkout,
      ...ptBrTimePicker,
      ...ptBrTokenType,
      ...ptBrUserMenu,
      ...ptBrWorkout,
      ...ptBrWorkoutDetail,
      ...ptBrWorkoutDetails,
      ...ptBrWorkoutHistory,
      ...ptBrWorkoutLog,
      ...ptBrWorkoutOptions,
      ...ptBrWorkoutSession,
      ...ptBrWorkoutSummary,
      ...ptBrWorkoutLogSets,
      ...ptBrWorkoutLogs,
      ...ptBrWorkoutTemplateSets,
      ...ptBrWorkouts,
    },
  },
  [RU_RU]: {
    translation: {
      ...untranslated,
      ...ruRuAccessToken,
      ...ruRuAddMeal,
      ...ruRuAi,
      ...ruRuBodyMetrics,
      ...ruRuBodyFat,
      ...ruRuCamera,
      ...ruRuCoach,
      ...ruRuCommon,
      ...ruRuCreateWorkout,
      ...ruRuCurrentGoalsCard,
      ...ruRuCycle,
      ...ruRuDailySummaryCard,
      ...ruRuDatePicker,
      ...ruRuEatingPhaseBadge,
      ...ruRuEditFitnessDetails,
      ...ruRuEditPersonalInfo,
      ...ruRuEditScreenInfo,
      ...ruRuEditSetDetails,
      ...ruRuEmptyStates,
      ...ruRuEndWorkout,
      ...ruRuErrors,
      ...ruRuExerciseGoals,
      ...ruRuExerciseTransition,
      ...ruRuExercises,
      ...ruRuExpiresIn,
      ...ruRuFocus,
      ...ruRuFood,
      ...ruRuFoodSearch,
      ...ruRuFoodFoodPortions,
      ...ruRuFreeTraining,
      ...ruRuGoalHistoryCard,
      ...ruRuGoalsManagement,
      ...ruRuHealthConnect,
      ...ruRuHeightPicker,
      ...ruRuHome,
      ...ruRuLogSetPerformance,
      ...ruRuMealFoods,
      ...ruRuMeals,
      ...ruRuNotifications,
      ...ruRuNutrition,
      ...ruRuNutritionGoals,
      ...ruRuNutritionLogs,
      ...ruRuOnboarding,
      ...ruRuOptionsSelector,
      ...ruRuPastWorkoutHistory,
      ...ruRuPortionSizes,
      ...ruRuProfile,
      ...ruRuProgress,
      ...ruRuReplaceExercise,
      ...ruRuRestOver,
      ...ruRuRestTimer,
      ...ruRuSessionFeedback,
      ...ruRuSettings,
      ...ruRuSnackbar,
      ...ruRuStartWorkout,
      ...ruRuTimePicker,
      ...ruRuTokenType,
      ...ruRuUserMenu,
      ...ruRuWorkout,
      ...ruRuWorkoutDetail,
      ...ruRuWorkoutDetails,
      ...ruRuWorkoutHistory,
      ...ruRuWorkoutLog,
      ...ruRuWorkoutOptions,
      ...ruRuWorkoutSession,
      ...ruRuWorkoutSummary,
      ...ruRuWorkoutLogSets,
      ...ruRuWorkoutLogs,
      ...ruRuWorkoutTemplateSets,
      ...ruRuWorkouts,
    },
  },
};

export type LanguageKeys = keyof typeof resources;

export const LOCALE_MAP = {
  [EN_US]: localeEnUS,
  [ES_ES]: localeEs,
  [NL_NL]: localeNl,
  [PT_BR]: localePtBR,
  [RU_RU]: localeRu,
};

export const AVAILABLE_LANGUAGES = Object.keys(resources) as LanguageKeys[];

const systemLocales = Localization.getLocales();

i18n.use(initReactI18next).init({
  // compatibilityJSON: 'v3',
  debug: __DEV__,
  fallbackLng: EN_US,
  interpolation: {
    escapeValue: false,
  },
  lng:
    systemLocales.find((locale) => AVAILABLE_LANGUAGES.includes(locale.languageTag as LanguageKeys))
      ?.languageTag || EN_US,
  resources,
});

export const languageLabels: Record<string, string> = {
  [EN_US]: i18n.t('untranslated.en-us.name'),
  [ES_ES]: i18n.t('untranslated.es-es.name'),
  [NL_NL]: i18n.t('untranslated.nl-nl.name'),
  [PT_BR]: i18n.t('untranslated.pt-br.name'),
  [RU_RU]: i18n.t('untranslated.ru-ru.name'),
};

export const LANDING_LANGUAGE_STORAGE_KEY = 'musclog_lang';

// Language multipliers for UI layout calculations based on IBM Globalization Design Guide expansion factors.
export const LANGUAGE_MULTIPLIERS: Record<string, number> = {
  'es-ES': 1.25,
  'nl-NL': 1.22,
  'pt-BR': 1.2,
  'ru-RU': 0.95,
};

// Mirror the active language to localStorage so the static landing panel
// (+html.tsx) can pick it up before React boots.
if (typeof window !== 'undefined' && typeof window.localStorage !== 'undefined') {
  i18n.on('languageChanged', (lng) => {
    try {
      window.localStorage.setItem(LANDING_LANGUAGE_STORAGE_KEY, lng);
    } catch (_) {
      // private/storage-full — ignore
    }
  });
}

export default i18n;
