/**
 * Dispatches rep-counting classification to a per-mechanic-type model,
 * falling back to the general (all-exercise) model when the given mechanic
 * type has no dedicated model.
 *
 * Hand-written — NOT regenerated by `npm run sync-ml-model`. Only the
 * model_*.js / manifest.json files in this directory are auto-generated by
 * training-data/train.py; this file just wires them together. Mechanic
 * types without enough training data yet get a model_<type>.js that simply
 * re-exports model_general.js (see training-data/train.py
 * `_write_fallback_js`), so every entry below always resolves to a working
 * classifier even before dedicated per-type training data exists.
 */
import { classifySegment as classifySegmentCardio } from './model_cardio';
import { classifySegment as classifySegmentCompound } from './model_compound';
import { classifySegment as classifySegmentGeneral } from './model_general';
import { classifySegment as classifySegmentIsolation } from './model_isolation';
import { classifySegment as classifySegmentMobility } from './model_mobility';
import { classifySegment as classifySegmentOther } from './model_other';
import { classifySegment as classifySegmentPlyometric } from './model_plyometric';
import { classifySegment as classifySegmentStretching } from './model_stretching';
import { classifySegment as classifySegmentUnknown } from './model_unknown';

type Classifier = (input: number[]) => [number, number];

const MODEL_BY_MECHANIC_TYPE: Record<string, Classifier> = {
  cardio: classifySegmentCardio,
  compound: classifySegmentCompound,
  isolation: classifySegmentIsolation,
  mobility: classifySegmentMobility,
  other: classifySegmentOther,
  plyometric: classifySegmentPlyometric,
  stretching: classifySegmentStretching,
  unknown: classifySegmentUnknown,
};

/**
 * classifySegment(features, mechanicType)[1] > 0.5  →  is a real rep.
 * `mechanicType` is matched case-insensitively against the mechanic types
 * trained in training-data/train.py; anything missing/unrecognised uses the
 * general model.
 */
export function classifySegment(input: number[], mechanicType?: string): [number, number] {
  const key = (mechanicType ?? 'unknown').trim().toLowerCase();
  const model = MODEL_BY_MECHANIC_TYPE[key] ?? classifySegmentGeneral;
  return model(input);
}
