// @ts-nocheck
/* eslint-disable */
/*
 * auto-generated by train.py — do not edit.
 *
 * Maps a canonical mechanic type to a loader for its dedicated classifier.
 * Only mechanic types that earned a dedicated model appear here; every other
 * type is routed to `general` by the dispatcher in ./index.ts.
 *
 * Loaders are thunks rather than imports on purpose: each m2cgen forest is
 * ~500 KB of JavaScript and a session only ever classifies one or two mechanic
 * types, so a forest is parsed on first use instead of at bundle-eval time.
 *
 * Dedicated models in this build: (none — every mechanic type uses general)
 */
const MODEL_LOADERS = {
  general: () => require('./model_general.js').classifySegment,
};

export { MODEL_LOADERS };
