// @ts-nocheck
/* eslint-disable */
/*
 * auto-generated by train.py — do not edit.
 * No dedicated model for mechanic type "unknown" (no training run has produced
 * one yet — needs enough labeled recordings, see MIN_RECORDINGS_PER_MECHANIC
 * in training-data/train.py).
 * Falls back to the general (all-exercise) model. Re-run
 * `npm run update-reps-model` once training-data/raw-data has enough
 * labeled recordings for this mechanic type.
 */
import { classifySegment } from './model_general.js';
export { classifySegment };
